src/fullcalendar/urls.py
__author__ = 'jona'

from django.conf.urls import url, patterns

urlpatterns = patterns('fullcalendar.views',
                       url(r'^new/$', "new_calendar", name="new_calendar"),
                       url(r'^view/(?P<slug>[-\w]+)/(?P<calendar_id>\d+)/$', "view_calendar", name="view_calendar"),
                       url(r'^events/(?P<calendar_id>\d+)/$', "events_json", name="events_json"),
                       url(r'^event/save/(?P<slug>[-\w]+)$', "save_event", name="save_event"),
                       url(r'^event/$', "get_event", name="get_event"),
                       url(r'^event/update/', "update_event", name="update_event"),
                       url(r'^settings/(?P<slug>[-\w]+)/$', "settings_calendar", name="settings_calendar")
                       )

src/gym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
import forms_builder.forms.urls

from gym import settings

urlpatterns = [
                  url(r'^', include('main.urls', namespace="main")),
                  url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                  url(r'^members/', include('members.urls', namespace="members")),
                  url(r'^memberships/', include('memberships.urls', namespace="memberships")),
                  url(r'^diary/', include('diary.urls', namespace="diary")),
                  url(r'^store/', include('store.urls', namespace="store")),
                  url(r'^calendar/', include('fullcalendar.urls', namespace="calendar")),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^forms/', include(forms_builder.forms.urls)),
                  url(r'^qualification/', include('qualification.urls', namespace='qualification'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'main.views.custom_403'

src/members/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('members.views',
    url(r'^home/', "home", name="home"),
    url(r'^members_json/', "members_json", name="members_json"),
    url(r'^prospectus/', "prospectus", name="prospectus"),
    url(r'^prospectus_json/', "prospectus_json", name="prospectus_json"),
    url(r'^search/', "search", name="search"),
    url(r'^last-10-to-enter/', "last_10_to_enter", name="last_10_to_enter"),

    # url(r'^prospectus/', "prospectus", name="prospectus"),

     url(r'^new/', "new", name="new"),
     url(r'^edit/(?P<id>\d+)/$', 'edit', name='edit'),
     url(r'^delete/(?P<id>\d+)/$', 'delete', name='delete'),
     url(r'^add_membership/(?P<person_id>\d+)/$', 'add_membership', name='add_membership'),
     url(r'^edit_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'edit_membership', name='edit_membership'),
     url(r'^freeze_membership/(?P<person_id>\d+)/(?P<person_membership_id>\d+)/$', 'freeze_membership', name='freeze_membership'),
     url(r'^delete_freeze_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'delete_freeze_membership', name='delete_freeze_membership'),
     url(r'^delete_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'delete_membership', name='delete_membership'),
     url(r'^add_prospectus/(?P<person_id>\d+)/$', 'add_prospectus', name='add_prospectus'),
     url(r'^contract/(?P<person_membership_id>\d+)/$', 'contract', name='contract'),
     url(r'^details/(?P<person_id>\d+)/$', 'person_details', name='person_details'),
     url(r'^add-attendance/(?P<person_id>\d+)/$', 'add_attendance', name='add_attendance'),
     url(r'^add-exercise/', 'add_exercise', name='add_exercise'),
     url(r'^edit-voucher/(?P<person_membership_id>\d+)/$', 'edit_voucher', name='edit_voucher'),
     url(r'^members-json/', "get_members", name="get_members"),

)

src/fullcalendar/models.py
import datetime
from django.contrib.auth.models import Group, User
from django.db import models
from django.template import defaultfilters
from main.models import Person
from django.utils.translation import ugettext as _


class Calendar(models.Model):
    title = models.CharField(_('title'), max_length=200, null=False, blank=None)
    slug = models.SlugField(max_length=100)
    assigned = models.ForeignKey(User, null=True, verbose_name=_('assigned to'))
    users = models.ManyToManyField(User, related_name="users", verbose_name=_('shared with'))
    min_time = models.TimeField(_('min time'), null=True, blank=True)
    max_time = models.TimeField(_('max time'), null=True, blank=True)
    created_by = models.ForeignKey(User, related_name="created_by")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Calendar')
        verbose_name_plural = _('Calendars')
        permissions = (
            ("view_calendars", "Can see existing calendars"),
        )

    def save(self, *args, **kwargs):
        if not self.id and not self.slug:
            slug = defaultfilters.slugify(self.title)
            slug_exists = True
            counter = 1
            self.slug = slug
            while slug_exists:
                try:
                    slug_exists = Calendar.objects.get(slug=slug)
                    if slug_exists:
                        slug = self.slug + '_' + str(counter)
                        counter += 1
                except Calendar.DoesNotExist:
                    self.slug = slug
                    break
        super(Calendar, self).save(*args, **kwargs)


class Accessibility(models.Model):
    calendar = models.ForeignKey(Calendar)
    group = models.ForeignKey(Group)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Events(models.Model):
    calendar = models.ForeignKey(Calendar)
    event_start = models.DateTimeField()
    event_end = models.DateTimeField()
    title = models.CharField(max_length=200)
    description = models.TextField()
    observation = models.TextField(blank=True, null=True)
    member = models.ForeignKey(User)
    is_cancelled = models.BooleanField(default=False)

    created_by = models.ForeignKey(User, related_name="created_by_event")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

src/main/models.py
from datetime import date, datetime

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Model, Sum
from django.db.models.fields.related import ForeignKey
from django.forms import TimeInput
from django.utils import timezone
from django.utils.translation import ugettext as _
from forms_builder.forms.models import FormEntry

from accounts.models import Person
from store.models import Product, VoucherProduct

DAYS = 1
WEEKS = 2
MONTHS = 3
YEARS = 4
VISITS = 5

DURATION_TYPES = (
    (DAYS, _('Days')),
    (WEEKS, _('Weeks')),
    (MONTHS, _('Months')),
    (YEARS, _('Years')),
    (VISITS, _('Visits')),
)

ANY = 0
ONCE = 1
TWICE = 2
THREE_TIMES = 3

ENTRIES_LIMIT_DAILY = (
    (ANY, _('Any')),
    (ONCE, _('ONCE')),
    (TWICE, _('TWICE')),
    (THREE_TIMES, _('THREE_TIMES')),
)


class Membership(Model):
    product = models.ForeignKey(Product)
    duration_frequency = models.IntegerField(_('times'), null=False, blank=None)
    duration_type = models.IntegerField(_('month,day,year'), choices=DURATION_TYPES, default=MONTHS)
    limit_visits_per_day = models.IntegerField(_('limit visits per day'), choices=ENTRIES_LIMIT_DAILY, default=ANY)
    is_on_monday = models.BooleanField(_('monday'), default=True)
    is_on_tuesday = models.BooleanField(_('tuesday'), default=True)
    is_on_wednesday = models.BooleanField(_('wednesday'), default=True)
    is_on_thursday = models.BooleanField(_('thursday'), default=True)
    is_on_friday = models.BooleanField(_('friday'), default=True)
    is_on_saturday = models.BooleanField(_('saturday'), default=True)
    is_on_sunday = models.BooleanField(_('sunday'), default=True)

    is_active = models.BooleanField(_('is active'), default=True)
    is_promo = models.BooleanField(_('is promo'), default=False)
    date_end = models.DateField(_('end at'), null=True, blank=True)

    from_time = models.TimeField()
    to_time = models.TimeField()
    # is_limit_time = models.BooleanField(default=False)
    # TODO implement period durant the day

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Membership')
        verbose_name_plural = _('Memberships')
        permissions = (
            ("view_memberships", "Can see existing memberships"),
            ("view_seller_team", "Can see seller team"),
        )

    def __str__(self):
        return self.product.name

    def get_count_members(self):
        return PersonMembership.objects.filter(membership=self).count()

    def allowed_days(self):
        days = ''
        if self.is_on_monday:
            days += 'L '
        if self.is_on_tuesday:
            days += 'M '
        if self.is_on_wednesday:
            days += 'W '
        if self.is_on_thursday:
            days += 'J '
        if self.is_on_friday:
            days += 'V '
        if self.is_on_saturday:
            days += 'S '
        if self.is_on_sunday:
            days += 'D '
        return days


class PersonMembership(Model):
    person = ForeignKey(Person)
    membership = ForeignKey(Membership)
    observation = models.TextField(_('target person'), blank=True, null=True)
    since = models.DateField(_('since'), default=timezone.now, null=False)
    to = models.DateField(_('to'), null=False)
    to_real = models.DateField(_('to'), null=False, default=timezone.now)
    active = models.BooleanField(default=False)
    voucher_product = models.ForeignKey(VoucherProduct, null=True)
    contract_number = models.CharField(max_length=10)

    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, related_name='person_membership_created_by')

    class Meta:
        verbose_name = _('Person Membership')
        verbose_name_plural = _('People Memberships')

        permissions = (
            ("view_who_created_member", "Can see who create a member"),
            ("view_last_10_memberships", "Can view last 10 membership acquired by a  person"),
            ("report_added_people_by_users", "Can see report about person added by users.")
        )


class FrozenPersonMembership(Model):
    number = models.CharField(null=False, blank=False, max_length=20)
    person_membership = ForeignKey(PersonMembership)
    since = models.DateField(_('since'), null=False)
    to = models.DateField(_('to'), null=False)

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(User, related_name='frozen_person_membership_created_by')

    class Meta:
        verbose_name = _('Person Membership Frozen')
        verbose_name_plural = _('People Memberships Frozen')


PersonMembership.freezing = property(lambda s: FrozenPersonMembership.objects.filter(person_membership=s))

User.count_sales_in_month = property(
    lambda s: PersonMembership.objects.filter(created_by=s, created_at__year=datetime.today().year,
                                              created_at__month=datetime.today().month).count())

User.total_sales_in_month = property(
    lambda s: PersonMembership.objects.filter(created_by=s, created_at__year=datetime.today().year,
                                              created_at__month=datetime.today().month).aggregate(
        Sum('membership__product__price'))['membership__product__price__sum'])


class Prospectus(Model):
    person = ForeignKey(Person)
    entry = ForeignKey(FormEntry)
    close_sale = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Prospectus')
        verbose_name_plural = _('Prospectus')


class Event(Model):
    key = models.SlugField(max_length=100, null=False, blank=None)
    value = models.CharField(max_length=100, null=False, blank=None)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        permissions = (
            ("views_tasks", "Can view tasks assigned to him"),
        )


class Task(Model):
    event = models.ForeignKey(Event, null=True, blank=True)
    action = models.CharField(max_length=100, null=False, blank=None)
    description = models.TextField(null=True, blank=True)
    duration_frequency = models.IntegerField(null=False, blank=None)
    duration_type = models.IntegerField(choices=DURATION_TYPES, default=1)
    default_done = models.BooleanField(default=False)
    is_preventive = models.BooleanField(default=False)

    active = models.BooleanField(default=True)

    def __str__(self):
        return self.event.value + ", " + self.action

    def natural_key(self):
        return (self.event.value, self.action, self.description)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')


class UserTask(Model):
    task = models.ForeignKey(Task, null=True, blank=True)
    user = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.CharField(_('id'), max_length=200, blank=True, null=True)
    object_repr = models.CharField(_('reference'), max_length=200)
    date = models.DateField()
    date_done = models.DateField(null=True, blank=True)
    date_postpone = models.DateField(null=True, blank=True)
    resume = models.TextField(null=False, blank=True)
    done = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task.__str__()

    class Meta:
        verbose_name = _('Tarea de usuario')
        verbose_name_plural = _('Tareas de usuarios')


class Exercise(Model):
    name = models.CharField(_('name'), max_length=20)
    description = models.TextField(_('descripcion'), )
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Exercise')
        verbose_name_plural = _('Exercises')


class Attendance(Model):
    person_membership = models.ForeignKey(PersonMembership, null=True)
    exercises = models.ManyToManyField(Exercise)

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(User)

    class Meta:
        verbose_name = _('Attendance')
        verbose_name_plural = _('Attendances')
        permissions = (
            ("view_last_10_attendances", "Can view last 10 attendances per person"),
            ("add_exercise_to_attendance", "Can add exercise to attendance"),
        )

    def is_past_due(self):
        if date.today() > self.created_at.date():
            return True
        return False

    def __unicode__(self):
        return self.created_at


Person.get_active_membership_of_person = property(
    lambda s: PersonMembership.objects.filter(person=s, to__gt=timezone.now).first())

Person.last_attendance = property(
    lambda s: Attendance.objects.filter(person_membership__person=s).order_by('-created_at').first())

src/fullcalendar/templates/fullcalendar/calendar.html
{% extends 'main/layout.html' %}

{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'fullcalendar/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}"/>
    <link href="{% static 'fullcalendar/plugins/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'fullcalendar/fullcalendar/lib/cupertino/jquery-ui.min.css' %}" rel="stylesheet"/>
{% endblock %}

{% block page_toolbar %}
    <div class="btn-group pull-right">
        <a href="{% url 'calendar:settings_calendar' slug %}" class="btn btn-fit-height blue-ebonyclay">
            <i class="glyphicon glyphicon-cog"></i>
            {% trans 'Settings' %}
        </a>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green-meadow calendar">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>{% trans "calendar"|capfirst %}
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div id="calendar" class="has-toolbar">
                            </div>
                        </div>
                    </div>
                    <!-- END CALENDAR PORTLET-->
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="event" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Event</h4>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'calendar:save_event' slug %}" id="event-form">
                        <div class="form-group form-md-line-input has-success form-md-floating-label">
                            <div class="input-icon">
                                {% csrf_token %}
                                <input type="hidden" id="id_event" name="id" value="">
                                {{ form_event.title }}
                                <label for="form_control_1">{% trans 'Title' %}</label>
                                <span class="help-block"></span>
                                <i class="fa fa-bell-o"></i>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input has-success form-md-floating-label">
                            <div class="input-group">
                                <div class="input-group-control">
                                    {{ form_event.event_start|add_class:"datetime" }}
                                    <label for="form_control_1">{% trans 'Start' %}</label>
                                </div>
                        <span class="input-group-btn btn-right">
                            <span class="glyphicon glyphicon-minus"></span>
                        </span>

                                <div class="input-group-control">
                                    {{ form_event.event_end|add_class:"datetime" }}
                                    <label for="form_control_1">{% trans 'End' %}</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input has-success form-md-floating-label">
                            <div class="input-icon">
                                <input class="form-control" id="id_member" maxlength="100" type="text">
                                <input name="member" type="hidden">
                                <label for="form_control_1">{% trans 'Member' %}</label>
                                <span class="help-block"></span>
                                <i class="fa fa-bell-o"></i>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input has-success form-md-floating-label">
                            <div class="input-icon">
                                {{ form_event.description }}
                                <label for="form_control_1">{% trans 'Description' %}</label>
                                <span class="help-block"></span>
                                <i class="fa fa-bell-o"></i>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input has-success form-md-floating-label">
                            <div class="input-icon">
                                {{ form_event.observation }}
                                <label for="form_control_1">{% trans 'Observation' %}</label>
                                <span class="help-block"></span>
                                <i class="fa fa-bell-o"></i>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">{% trans "close"|capfirst %}</button>
                    <button type="submit" class="btn blue"
                            form="event-form">{% trans "save changes"|capfirst %}</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
{% endblock %}

{% block javascripts_plugins %}
    <script src="{% static 'fullcalendar/plugins/moment.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'fullcalendar/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'fullcalendar/plugins/fullcalendar/fullcalendar.js' %}"></script>
{% endblock %}

{% block javascripts_custom %}
    <script>
        $(document).ready(function () {
            var format = 'DD/MM/YYYY hh:mm a';
            $('#calendar').fullCalendar({
                header: {
                    left: '',
                    center: 'title',
                    right: 'prev,next today,month,agendaWeek,agendaDay'
                },
                {% if calendar.max_time and calendar.min_time %}
                    maxTime: "{{ calendar.max_time }}" ,
                    minTime: "{{ calendar.min_time }}" ,
                {% endif %}
                timezone: false,
                editable: true,
                selectable: true,
                events: '{% url 'calendar:events_json' calendar_id %}',
                select: function (startDate, endDate) {
                    $('#event-form').trigger("reset");
                    $('#event-form .has-warning').removeClass('has-warning');
                    $('#id_event').val("");
                    $('#event').modal('show');
                    $('#id_event_start').val(moment(startDate).format(format)).addClass('edited');
                    $('#id_event_end').val(moment(endDate).format(format)).addClass('edited');
                },
                eventClick: function (calEvent, jsEvent, view) {
                    $('#event-form').trigger("reset");
                    $('#id_event').val(calEvent.id);
                    $.ajax({
                        url: '{% url 'calendar:get_event' %}',
                        data: {
                            id: calEvent.id,
                            csrfmiddlewaretoken: "{{ csrf_token }}"
                        },
                        method: 'POST',
                        dataType: 'json',
                        success: function (response) {
                            if (response.success) {
                                $.each(response.data, function (index, value) {
                                    if (index == 'event_start' || index == 'event_end') {
                                        $('#id_' + index).val(
                                                moment(value).format(format)
                                        ).addClass('edited');
                                    } else if (index == 'member') {
                                        $('#event-form [name=member]').val(value);
                                        $('#id_member').val(response.data.member_fullname).addClass('edited');
                                    } else {
                                        $('#id_' + index).val(value).addClass('edited');
                                    }
                                });
                                $('#event').modal('show');

                            } else {
                                console.log(response.message);
                            }
                        }

                    });
                },
                eventDrop: function (event, delta, revertFunc, jsEvent, ui, view) {
                    sendEvent(event.id, event.title, event.start, event.end, event.allDay);
                },
                eventResize: function (event, delta, reverFunc, jsEvent, ui, view) {
                    sendEvent(event.id, event.title, event.start, event.end, event.allDay);
                }

            });

            var sendEvent = function (id, title, start, end, allDay) {
                $.ajax({
                    url: '{% url 'calendar:update_event' %}',
                    method: 'post',
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        id: id,
                        title: title,
                        start: moment(start).format(format),
                        end: moment(end).format(format),
                        allDay: allDay
                    },
                    dataType: 'json',
                    success: function (response) {
                        console.log(response);
                    }
                });
            };

            $('#event-form').on('submit', function (e) {
                e.preventDefault();
                var url = $(this).attr('action');
                var method = $(this).attr('method');
                var data = $(this).serializeArray();

                $.ajax({
                    url: url,
                    method: method,
                    data: data,
                    dataType: 'json',
                    success: function (response) {
                        if (response.success) {
                            var w = $('#calendar').fullCalendar('clientEvents', response.id);
                            if (w.length == 0) {
                                $('#calendar').fullCalendar('renderEvent', {
                                    id: response.id,
                                    title: response.title,
                                    start: new Date(response.start),
                                    end: new Date(response.end),
                                    allDay: response.allDay
                                }, 'stick');
                            } else {
                                w[0].title = response.title;
                                w[0].start = new Date(response.start);
                                w[0].end = new Date(response.end);
                                w[0].allDay = response.allDay;
                                $('#calendar').fullCalendar('updateEvent', w[0]);
                            }

                            $('#event-form').trigger("reset");
                            $('#event').modal('hide');
                        } else {
                            $.each(response.errors, function (index, value) {
                                $('#id_' + value).addClass('edited').parents('.form-group').removeClass('has-success').addClass('has-warning');
                            });
                        }
                    }
                });
            });
            $('.datetime').datetimepicker({
                autoclose: true,
                format: 'dd/mm/yyyy HH:ii p',
                isRTL: Metronic.isRTL(),
                showMeridian: true,
                pickerPosition: (Metronic.isRTL()) ? "bottom-right" : "bottom-left",
                todayBtn: true
            });

            $("#id_member").autocomplete({
                source: function (request, response) {
                    $.get("{% url 'members:get_members' %}", {
                        pattern: request.term
                    }, function (data) {
                        var result = [];
                        for (var i = 0; i < data.length; i++) {
                            result.push({
                                label: data[i].name + ' ' + data[i].surname,
                                value: data[i].name + ' ' + data[i].surname,
                                user: data[i].user
                            })
                        }
                        response(result);
                    });
                },
                select: function (a, b) {
                    $('#event-form [name=member]').val(b.item.user);
                },
                minLength: 3,
                appendTo: "#event-form"
            });
        });
    </script>
{% endblock %}

src/fullcalendar/templates/fullcalendar/home.html
{% extends 'main/layout.html' %}

{% load static %}
{% load i18n %}

{% block stylesheets %}
<link href="{% static 'fullcalendar/plugins/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<div class="portlet-body">
    <div class="row">
        <div class="col-md-3 col-sm-12">
            <!-- BEGIN DRAGGABLE EVENTS PORTLET-->
            <h3 class="event-form-title">Draggable Events</h3>
            <div id="external-events">
                <form class="inline-form">
                    <input type="text" value="" class="form-control" placeholder="Event Title..." id="event_title"/><br/>
                    <a href="javascript:;" id="event_add" class="btn default">
                    Add Event </a>
                </form>
                <hr/>
                <div id="event_box">
                </div>
                <label for="drop-remove">
                <input type="checkbox" id="drop-remove"/>remove after drop </label>
                <hr class="visible-xs"/>
            </div>
            <!-- END DRAGGABLE EVENTS PORTLET-->
        </div>
        <div class="col-md-9 col-sm-12">
            <div id="calendar" class="has-toolbar">
            </div>
        </div>
    </div>
    <!-- END CALENDAR PORTLET-->
</div>
{% endblock %}

{% block javascripts_plugins %}
<script src="{% static 'fullcalendar/plugins/moment.min.js' %}"></script>
<script src="{% static 'fullcalendar/plugins/fullcalendar/fullcalendar.min.js' %}"></script>
{% endblock %}

{% block javascripts_custom %}
    <script>
        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: true,
            events: '{% url 'calendar:events_json' 11 %}'
        });
    </script>
{% endblock %}

src/fullcalendar/templates/fullcalendar/settings.html
{% extends 'main/layout.html' %}

{% load i18n %}
{% load main_extras %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% include 'hock/form.html' with form=form_calendar width=12 %}
        </div>
    </div>
{% endblock %}

{% block javascripts_plugins %}
{% endblock %}