src/gym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
import forms_builder.forms.urls

from gym import settings

urlpatterns = [
                  url(r'^', include('main.urls', namespace="main")),
                  url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                  url(r'^members/', include('members.urls', namespace="members")),
                  url(r'^memberships/', include('memberships.urls', namespace="memberships")),
                  url(r'^diary/', include('diary.urls', namespace="diary")),
                  url(r'^store/', include('store.urls', namespace="store")),
                  url(r'^calendar/', include('fullcalendar.urls', namespace="calendar")),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^forms/', include(forms_builder.forms.urls)),
                  url(r'^qualification/', include('qualification.urls', namespace='qualification'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'main.views.custom_403'

src/members/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('members.views',
    url(r'^home/', "home", name="home"),
    url(r'^members_json/', "members_json", name="members_json"),
    url(r'^prospectus/', "prospectus", name="prospectus"),
    url(r'^prospectus_json/', "prospectus_json", name="prospectus_json"),
    url(r'^search/', "search", name="search"),
    url(r'^last-10-to-enter/', "last_10_to_enter", name="last_10_to_enter"),

    # url(r'^prospectus/', "prospectus", name="prospectus"),

     url(r'^new/', "new", name="new"),
     url(r'^edit/(?P<id>\d+)/$', 'edit', name='edit'),
     url(r'^delete/(?P<id>\d+)/$', 'delete', name='delete'),
     url(r'^add_membership/(?P<person_id>\d+)/$', 'add_membership', name='add_membership'),
     url(r'^edit_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'edit_membership', name='edit_membership'),
     url(r'^freeze_membership/(?P<person_id>\d+)/(?P<person_membership_id>\d+)/$', 'freeze_membership', name='freeze_membership'),
     url(r'^delete_freeze_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'delete_freeze_membership', name='delete_freeze_membership'),
     url(r'^delete_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'delete_membership', name='delete_membership'),
     url(r'^add_prospectus/(?P<person_id>\d+)/$', 'add_prospectus', name='add_prospectus'),
     url(r'^contract/(?P<person_membership_id>\d+)/$', 'contract', name='contract'),
     url(r'^details/(?P<person_id>\d+)/$', 'person_details', name='person_details'),
     url(r'^add-attendance/(?P<person_id>\d+)/$', 'add_attendance', name='add_attendance'),
     url(r'^add-exercise/', 'add_exercise', name='add_exercise'),
     url(r'^edit-voucher/(?P<person_membership_id>\d+)/$', 'edit_voucher', name='edit_voucher'),
     url(r'^members-json/', "get_members", name="get_members"),

)

src/main/models.py
from datetime import date, datetime

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Model, Sum
from django.db.models.fields.related import ForeignKey
from django.forms import TimeInput
from django.utils import timezone
from django.utils.translation import ugettext as _
from forms_builder.forms.models import FormEntry

from accounts.models import Person
from store.models import Product, VoucherProduct

DAYS = 1
WEEKS = 2
MONTHS = 3
YEARS = 4
VISITS = 5

DURATION_TYPES = (
    (DAYS, _('Days')),
    (WEEKS, _('Weeks')),
    (MONTHS, _('Months')),
    (YEARS, _('Years')),
    (VISITS, _('Visits')),
)

ANY = 0
ONCE = 1
TWICE = 2
THREE_TIMES = 3

ENTRIES_LIMIT_DAILY = (
    (ANY, _('Any')),
    (ONCE, _('ONCE')),
    (TWICE, _('TWICE')),
    (THREE_TIMES, _('THREE_TIMES')),
)


class Membership(Model):
    product = models.ForeignKey(Product)
    duration_frequency = models.IntegerField(_('times'), null=False, blank=None)
    duration_type = models.IntegerField(_('month,day,year'), choices=DURATION_TYPES, default=MONTHS)
    limit_visits_per_day = models.IntegerField(_('limit visits per day'), choices=ENTRIES_LIMIT_DAILY, default=ANY)
    is_on_monday = models.BooleanField(_('monday'), default=True)
    is_on_tuesday = models.BooleanField(_('tuesday'), default=True)
    is_on_wednesday = models.BooleanField(_('wednesday'), default=True)
    is_on_thursday = models.BooleanField(_('thursday'), default=True)
    is_on_friday = models.BooleanField(_('friday'), default=True)
    is_on_saturday = models.BooleanField(_('saturday'), default=True)
    is_on_sunday = models.BooleanField(_('sunday'), default=True)

    is_active = models.BooleanField(_('is active'), default=True)
    is_promo = models.BooleanField(_('is promo'), default=False)
    date_end = models.DateField(_('end at'), null=True, blank=True)

    from_time = models.TimeField()
    to_time = models.TimeField()
    # is_limit_time = models.BooleanField(default=False)
    # TODO implement period durant the day

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Membership')
        verbose_name_plural = _('Memberships')
        permissions = (
            ("view_memberships", "Can see existing memberships"),
            ("view_seller_team", "Can see seller team"),
        )

    def __str__(self):
        return self.product.name

    def get_count_members(self):
        return PersonMembership.objects.filter(membership=self).count()

    def allowed_days(self):
        days = ''
        if self.is_on_monday:
            days += 'L '
        if self.is_on_tuesday:
            days += 'M '
        if self.is_on_wednesday:
            days += 'W '
        if self.is_on_thursday:
            days += 'J '
        if self.is_on_friday:
            days += 'V '
        if self.is_on_saturday:
            days += 'S '
        if self.is_on_sunday:
            days += 'D '
        return days


class PersonMembership(Model):
    person = ForeignKey(Person)
    membership = ForeignKey(Membership)
    observation = models.TextField(_('target person'), blank=True, null=True)
    since = models.DateField(_('since'), default=timezone.now, null=False)
    to = models.DateField(_('to'), null=False)
    to_real = models.DateField(_('to'), null=False, default=timezone.now)
    active = models.BooleanField(default=False)
    voucher_product = models.ForeignKey(VoucherProduct, null=True)
    contract_number = models.CharField(max_length=10)

    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, related_name='person_membership_created_by')

    class Meta:
        verbose_name = _('Person Membership')
        verbose_name_plural = _('People Memberships')

        permissions = (
            ("view_who_created_member", "Can see who create a member"),
            ("view_last_10_memberships", "Can view last 10 membership acquired by a  person"),
            ("report_added_people_by_users", "Can see report about person added by users.")
        )


class FrozenPersonMembership(Model):
    number = models.CharField(null=False, blank=False, max_length=20)
    person_membership = ForeignKey(PersonMembership)
    since = models.DateField(_('since'), null=False)
    to = models.DateField(_('to'), null=False)

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(User, related_name='frozen_person_membership_created_by')

    class Meta:
        verbose_name = _('Person Membership Frozen')
        verbose_name_plural = _('People Memberships Frozen')


PersonMembership.freezing = property(lambda s: FrozenPersonMembership.objects.filter(person_membership=s))

User.count_sales_in_month = property(
    lambda s: PersonMembership.objects.filter(created_by=s, created_at__year=datetime.today().year,
                                              created_at__month=datetime.today().month).count())

User.total_sales_in_month = property(
    lambda s: PersonMembership.objects.filter(created_by=s, created_at__year=datetime.today().year,
                                              created_at__month=datetime.today().month).aggregate(
        Sum('membership__product__price'))['membership__product__price__sum'])


class Prospectus(Model):
    person = ForeignKey(Person)
    entry = ForeignKey(FormEntry)
    close_sale = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Prospectus')
        verbose_name_plural = _('Prospectus')


class Event(Model):
    key = models.SlugField(max_length=100, null=False, blank=None)
    value = models.CharField(max_length=100, null=False, blank=None)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        permissions = (
            ("views_tasks", "Can view tasks assigned to him"),
        )


class Task(Model):
    event = models.ForeignKey(Event, null=True, blank=True)
    action = models.CharField(max_length=100, null=False, blank=None)
    description = models.TextField(null=True, blank=True)
    duration_frequency = models.IntegerField(null=False, blank=None)
    duration_type = models.IntegerField(choices=DURATION_TYPES, default=1)
    default_done = models.BooleanField(default=False)
    is_preventive = models.BooleanField(default=False)

    active = models.BooleanField(default=True)

    def __str__(self):
        return self.event.value + ", " + self.action

    def natural_key(self):
        return (self.event.value, self.action, self.description)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')


class UserTask(Model):
    task = models.ForeignKey(Task, null=True, blank=True)
    user = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.CharField(_('id'), max_length=200, blank=True, null=True)
    object_repr = models.CharField(_('reference'), max_length=200)
    date = models.DateField()
    date_done = models.DateField(null=True, blank=True)
    date_postpone = models.DateField(null=True, blank=True)
    resume = models.TextField(null=False, blank=True)
    done = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task.__str__()

    class Meta:
        verbose_name = _('Tarea de usuario')
        verbose_name_plural = _('Tareas de usuarios')


class Exercise(Model):
    name = models.CharField(_('name'), max_length=20)
    description = models.TextField(_('descripcion'), )
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Exercise')
        verbose_name_plural = _('Exercises')


class Attendance(Model):
    person_membership = models.ForeignKey(PersonMembership, null=True)
    exercises = models.ManyToManyField(Exercise)

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(User)

    class Meta:
        verbose_name = _('Attendance')
        verbose_name_plural = _('Attendances')
        permissions = (
            ("view_last_10_attendances", "Can view last 10 attendances per person"),
            ("add_exercise_to_attendance", "Can add exercise to attendance"),
        )

    def is_past_due(self):
        if date.today() > self.created_at.date():
            return True
        return False

    def __unicode__(self):
        return self.created_at


Person.get_active_membership_of_person = property(
    lambda s: PersonMembership.objects.filter(person=s, to__gt=timezone.now).first())

Person.last_attendance = property(
    lambda s: Attendance.objects.filter(person_membership__person=s).order_by('-created_at').first())

src/members/models.py
from django.db import models

# Create your models here.

src/members/forms.py
import datetime

from django.forms import ModelForm
from django.utils.translation import ugettext as _

from accounts.functions import get_users_of_seller_group
from main.functions import add_class_date_picker, add_class_edited, add_class_datetime_picker
from main.models import PersonMembership, Membership, FrozenPersonMembership


class PersonMembershipForm(ModelForm):
    form_meta = {'title': _('new person'), }

    class Meta:
        model = PersonMembership
        fields = ('membership', 'since', 'observation', 'created_by', 'created_at')

    def __init__(self, *args, **kwargs):
        super(PersonMembershipForm, self).__init__(*args, **kwargs)
        self.fields['since'].widget.format = '%d/%m/%Y'
        self.fields['since'].input_formats = ['%d/%m/%Y']
        self.fields['created_at'].widget.format = '%d/%m/%Y %H:%M'
        self.fields['created_at'].input_formats = ['%d/%m/%Y %H:%M']
        # self.fields['observation'].widget = Textarea(attrs={'placeholder': _('What is the person target with us?')})
        self.fields['observation'].widget.attrs['cols'] = 1
        self.fields['observation'].widget.attrs['rows'] = 1
        self.fields['membership'].queryset = Membership.objects.filter(is_active=True, is_promo=True,
                                                                       date_end__gte=datetime.date.today()) | Membership.objects.filter(
            is_promo=False, is_active=True)
        self.fields['created_by'].queryset = get_users_of_seller_group()
        add_class_edited(self, ['membership', 'since', 'observation', 'created_by'])
        add_class_date_picker(self, ['since'])
        add_class_datetime_picker(self, ['created_at'])


class PersonMembershipContractForm(ModelForm):
    class Meta:
        model = PersonMembership
        fields = ('contract_number',)


class FrozenPersonMembershipForm(ModelForm):
    form_meta = {'title': _('new frozen'), }

    class Meta:
        model = FrozenPersonMembership
        fields = ('since', 'to', 'number')

    def __init__(self, *args, **kwargs):
        super(FrozenPersonMembershipForm, self).__init__(*args, **kwargs)
        self.fields['since'].widget.format = '%d/%m/%Y'
        self.fields['since'].input_formats = ['%d/%m/%Y']
        self.fields['to'].widget.format = '%d/%m/%Y'
        self.fields['to'].input_formats = ['%d/%m/%Y']

        add_class_date_picker(self, ['since', 'to'])
        add_class_edited(self, ['number'])

src/members/templates/members/form.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% load static %}
{% load main_extras %}
{% block breadcrumb %}
    {% if member %}
        <li>
            <a href="{% url 'members:person_details' member.id %}">{% trans "person detail"|capfirst %}: {{ member.name }} {{ member.surname }}</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            {% trans title|capfirst %}
        </li>
    {% else %}
        <li>
            <a href="{% url 'members:home' %}">{% trans "people"|capfirst %}</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            {% trans title|capfirst %}
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'hock/form.html' with form=form title=title %}
{% endblock %}
{% block javascripts_custom %}

    <script src="{% static 'main/plugins/jquery-input-mask/dist/inputmask/inputmask.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'main/plugins/jquery-input-mask/dist/inputmask/inputmask.date.extensions.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'main/plugins/jquery-input-mask/dist/inputmask/jquery.inputmask.js' %}"
            type="text/javascript"></script>
{% endblock %}
{% block scripts %}

    $('.date-picker').each(function () {
    $(this).inputmask("d/m/y", {"placeholder": "dd/mm/yyyy"});
    });

    {% for field in fields %}
        if ($('#id_{{ field.slug }}').val() == ''){
        if ($('#id_{{ field.slug }}').hasClass('date-picker')){
        {% if field|get_value_from_items:entries %}
            $('#id_{{ field.slug }}').datepicker('setDate', new Date('{{ field|get_value_from_items:entries }}'));
        {% endif %}
        {#                $('#id_{{ field.slug }}').val('{{ field|get_value_from_items_in_date_format:entries }}');#}
        }else{
        $('#id_{{ field.slug }}').val('{{ field|get_value_from_items:entries }}');
        }
        $('#id_{{ field.slug }}').addClass('edited');
        }
    {% endfor %}
{% endblock %}

src/members/templates/members/form_freeze_membership.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
{% endblock %}
{% block breadcrumb %}
    <li>
        <a href="{% url 'members:person_details' person.id %}">{% trans "person detail"|capfirst %}: {{ person.name }} {{ person.surname }}</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        {% trans title|capfirst %}
    </li>
{% endblock %}
{% block content %}
    {% include 'hock/form.html' with form=form title=title %}
{% endblock %}
{% block javascripts_custom %}
    <script src="{% static 'main/plugins/jquery-input-mask/dist/inputmask/inputmask.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'main/plugins/jquery-input-mask/dist/inputmask/inputmask.date.extensions.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'main/plugins/jquery-input-mask/dist/inputmask/jquery.inputmask.js' %}"
            type="text/javascript"></script>
{% endblock %}
{% block scripts %}
    $('.date-picker').each(function () {
        $(this).inputmask("d/m/y", {"placeholder": "dd/mm/yyyy"});
    });
{% endblock %}

src/members/templates/members/form_observation.html
{% extends 'main/base_container.html' %}
{% block content %}
    <div class="container-narrow">

        <h1 class="title">{% if not member %} {{ form.form_meta.title }}{% else %} Agregando observation a {{ member.name }} {% endif %}</h1>

        <form role="form" action="." method="post" enctype="multipart/form-data" class="horizontal">
            {% csrf_token %}
            <fieldset>
                <legend>
                    Membresia
                </legend>
                {% include 'hock/form_horizontal.html' with form=form %}
            </fieldset>
            <div>
                <input type="submit" value="Guardar"/>
            </div>
        </form>
    </div>
{% endblock %}

src/members/templates/members/home.html
{% extends 'main/layout.html' %}

{% load thumbnail %}
{% load i18n %}
{% load main_extras %}

{% block search_page %}
    <!-- BEGIN HEADER SEARCH BOX -->
    <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
<form class="search-form search-form-expanded" action="{% url 'members:search' %}" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="{% trans 'search by name or dni' %}"
                           id="_search"
                           name="pattern" required/>
					<span class="input-group-btn">
					<button class="btn submit"><i class="icon-magnifier"></i></button>
					</span>
                </div>
            </form>
    <!-- END HEADER SEARCH BOX -->
{% endblock %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'members:home' %}">{% trans title|capfirst %}</a>
    </li>
{% endblock %}

{% block page_toolbar %}
    <a href="{% url 'members:new' %}" class="btn btn-fit-height blue pull-right">
        <span class="fa fa-plus"></span>
        {% trans 'create person'|capfirst %}
    </a>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'members:last_10_to_enter' %}" class="btn btn-circle btn-default ">
                <i class="icon-users"></i>
                {% trans 'last 10 visit'|capfirst %}
            </a>
        </div>
        <div class="col-md-6">

        </div>
    </div>
    <br>
    <div class="row">
        {% for member in members %}
            {% with person_membership=member.person.get_active_membership_of_person %}
                <div class="col-md-4">
                <!-- START widget-->
                  <div class="panel widget">
                     <div class="panel-body">
                        <div class="row row-table">
                           <div class="col-xs-6 text-center">
                               {% thumbnail member.person.image "96x96" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="Image" class="img-circle thumb96"/>
                                {% endthumbnail %}
                           </div>
                           <div class="col-xs-6">
                              <h3 class="mt0">
                                  <a href="{% url 'members:person_details' member.person.id %}">
                                    {{ member.person.name|first_word }} <br>{{ member.person.surname|first_word }}
                                  </a>
                              </h3>
                              <ul class="list-unstyled">
                                 <li class="mb-sm">
                                    <em class="fa fa-phone fa-fw"></em>{{ member.person.cellphone|default:'cel. no registrado' }}</li>
                                 <li class="mb-sm">
                                    <em class="fa fa-user fa-fw"></em>{{ member.person.nick|default:'sobrenombre no registrado' }}</li>
                                 <li class="mb-sm">
                                    <em class="fa fa-credit-card fa-fw"></em>{{ person_membership.membership.product.name }}</li>
                                 <li class="mb-sm">
                                    <em class="fa fa-calendar fa-fw"></em>{% trans 'period'|capfirst %}<br>
                                            {% trans 'from'|capfirst %}: {{ person_membership.since|date:"d-M-y" }} <br>
                                            {% trans 'to'|capfirst %}: {{ person_membership.to|date:"d-M-y" }}
                                 </li>
                                 <li class="mb-sm">
                                    <em class="fa fa-male fa-fw"></em>{{ member.person.created_by }}
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="panel-body bg-blue-ebonyclay">
                        <div class="row row-table text-center">
                           <div class="col-xs-4">
                              <p class="m0 h3">
                                  <a href="{% url 'members:add_membership' member.person.id %}" class="btn btn-icon-only yellow-gold">
                                    <i class="fa fa-users"></i>
                                  </a>
                              </p>
                              <p class="m0 text-muted">{% trans 'add'|capfirst %} {% trans 'membership'|capfirst %}</p>
                           </div>
                           <div class="col-xs-4">
                              <p class="m0 h3">
                                  <a href="{% url 'members:add_attendance' member.person.id %}?keep_url=true" class="btn btn-icon-only green-jungle">
                                    <i class="fa fa-check"></i>
                                  </a>
                              </p>
                              <p class="m0 text-muted">{% trans 'add'|capfirst %} {% trans 'attendance'|capfirst %}</p>
                           </div>
                           <div class="col-xs-4">
                              <p class="m0 h3">
                                  {% if member.person.last_attendance %}
                                        {{ member.person.last_attendance.created_at|date:'d-b H:i' }}
                                  {% else %}
                                        00-00 00:00
                                  {% endif %}</p>
                              <p class="m0 text-muted">{% trans 'last visit'|capfirst %}</p>
                           </div>
                        </div>
                     </div>
                  </div>

                  <!-- END widget-->
                </div>

{#                <div class="col-md-4">#}
{#                    <!-- BEGIN Portlet PORTLET-->#}
{#                    <div class="portlet light {% if member.person.birthday|is_birthday %}birthday{% endif %}">#}
{#                        <div class="portlet-title">#}
{#                            <div class="caption font-green-sharp">#}
{#                                <a href="{% url 'members:person_details' member.person.id %}">#}
{#                                    <i class="icon-speech font-green-sharp"></i>#}
{#                                    <span class="caption-subject"> {{ member.person.name }} {{ member.person.surname }}</span>#}
{#                                    <span class="caption-helper">@{{ member.person.nick }}</span>#}
{#                                </a>#}
{#                            </div>#}
{#                            <div class="actions">#}
{#                                <div class="btn-group">#}
{#                                    <a class="btn btn-circle btn-default " href="javascript:;" data-toggle="dropdown">#}
{#                                        <i class="fa fa-tasks"></i> {% trans 'Options' %} <i#}
{#                                            class="fa fa-angle-down"></i>#}
{#                                    </a>#}
{#                                    <ul class="dropdown-menu pull-right">#}
{#                                        <li>#}
{#                                            <a href="{% url 'members:add_attendance' member.person.id %}?keep_url=true">#}
{#                                                <i class="fa fa-check"></i> {% trans 'add'|capfirst %} {% trans 'attendance'|capfirst %} {% trans 'for today'|capfirst %}#}
{#                                            </a>#}
{#                                        </li>#}
{#                                        <li>#}
{#                                            <a href="{% url 'members:add_membership' member.person.id %}">#}
{#                                                <i class="fa fa-plus"></i> {% trans 'add'|capfirst %} {% trans 'membership'|capfirst %}#}
{#                                            </a>#}
{#                                        </li>#}
{#                                        <li>#}
{#                                            <a href="{% url 'members:person_details' member.person.id %}">#}
{#                                                <i class="fa fa-gear"></i> {% trans 'details'|capfirst %} </a>#}
{#                                        </li>#}
{#                                    </ul>#}
{#                                </div>#}
{#                                <a class="btn btn-circle btn-default"#}
{#                                   href="{% url 'members:add_attendance' member.person.id %}?keep_url=true"#}
{#                                   title="{% trans 'add'|capfirst %} {% trans 'attendance'|capfirst %} {% trans 'for today'|capfirst %}">#}
{#                                    <i class="fa fa-check"></i>#}
{#                                </a>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="portlet-body">#}
{#                            <div class="scroller" style="height:400px" data-rail-visible="1" data-rail-color="yellow"#}
{#                                 data-handle-color="#a1b2bd">#}
{#                                <div class="thumbnail">#}
{#                                    {% thumbnail member.person.image "209x200" crop="center" as im %}#}
{#                                        <img src="{{ im.url }}"/>#}
{#                                    {% endthumbnail %}#}
{#                                </div>#}
{#                                <ul class="list-group">#}
{#                                    <li class="list-group-item">#}
{#                                        {% if person_membership %}#}
{#                                            <b>{% trans 'membership'|capfirst %}</b>:#}
{#                                            {{ person_membership.membership.product.name }} <br/>#}
{#                                            {% trans 'period'|capfirst %}:  {% trans 'from' %}#}
{#                                            {{ person_membership.since|date:"d-M-y" }} {% trans 'to' %}#}
{#                                            {{ person_membership.to|date:"d-M-y" }} <br/>#}
{##}
{#                                            {% if perms.main.view_who_created_member %}#}
{#                                                {% trans 'added by'|capfirst %}:#}
{#                                                {{ person_membership.created_by.first_name }} <br/>#}
{#                                            {% endif %}#}
{#                                        {% else %}#}
{#                                            {% trans 'any membserhip currently' %}#}
{#                                        {% endif %}#}
{#                                    </li>#}
{#                                    <li class="list-group-item">{% trans 'last visit'|capfirst %}:#}
{#                                        {% if member.person.last_attendance %}#}
{#                                            {{ member.person.last_attendance.created_at|date:'d-b H:i' }}#}
{#                                        {% endif %}#}
{#                                    </li>#}
{#                                    {% if member.person.birthday|is_birthday %}#}
{#                                        <li class="list-group-item">#}
{#                                            {% trans 'important'|capfirst %}:#}
{#                                            <b>#}
{#                                                {% blocktrans with name=member.person.name surname=member.person.surname years_old=member.person.birthday|years_old %}#}
{#                                                    today is the birthday of {{ name }} {{ surname }}, {{ years_old }}#}
{#                                                {% endblocktrans %} years old</b>#}
{#                                        </li>#}
{#                                    {% endif %}#}
{#                                    <li class="list-group-item">{% trans 'person added by'|capfirst %}:#}
{#                                        {{ member.person.created_by }}#}
{#                                    </li>#}
{#                                </ul>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <!-- END Portlet PORTLET-->#}
{#                </div>#}
            {% endwith %}
        {% endfor %}
    </div>

    {% if members.count == 0 %}
        <p class="text-center">
            <em>{% trans 'not found person' %}</em>
        </p>
    {% endif %}

{% endblock %}

{% block scripts %}
    Demo.init('members');
    $('.delete_link').click(function (e) {
    if (!confirm("Are you sure?")) {
    e.preventDefault();
    return false;
    }
    });

    $('#_search').focus();
{% endblock %}