src/accounts/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext as _

from accounts.forms import PasswordResetFormEdited, \
    SetPasswordFormEdited


urlpatterns = patterns('accounts.views',
    url(r'^message/(?P<code>[-\w]+)/$', 'message', name='message'),
    # url('^register/', CreateView.as_view(
    #         template_name='accounts/register.html',
    #         form_class=UserCreationForm,
    #         success_url='/'
    # ),name="register"),
    url('^new/','new',name='new'),
    url('^list/','_list',name='list'),
    url('^accounts_json/','accounts_json',name='accounts_json'),

    url(r'^edit/(?P<id>\d+)/$', 'edit', name='edit'),
    url(r'^delete/(?P<id>\d+)/$', 'delete', name='delete'),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {
        'template_name': 'accounts/login.html',
        'extra_context': {
            'page': {
                'title': _('Log in'),
            },
        }
    }, name='login'),
    url(r'^logout/$', 'logout', {
        'next_page': '/',
    }, name='logout'),
    url(r'^profile/password/reset/$', 'password_reset', {
        'template_name': 'accounts/page_form.html',
        'password_reset_form': PasswordResetFormEdited,
        'post_reset_redirect':'/accounts/message/password_reset/',
        'email_template_name': 'accounts/email_reset.html',
        'extra_context': {
            'page': {
                'title': _('Reset password'),
            }
        }
    }, name='password_reset'),
    url(r'^profile/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'password_reset_confirm', {
            'template_name': 'accounts/page_form.html',
            'set_password_form': SetPasswordFormEdited,
            'post_reset_redirect': '/accounts/message/password_reset_confirm/',
        }, 'password_reset_confirm',),
)

src/diary/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('diary.views',
    url(r'^home/', 'home', name='home'),
    url(r'^new/', 'new', name='new'),
    url(r'^tasks/todo', 'tasks_todo', name='tasks_todo'),
    url(r'^tasks/done', 'tasks_done', name='tasks_done'),
    url(r'^tasks/postpone', 'tasks_postpone', name='tasks_postpone'),
    url(r'^get_tasks/', 'get_tasks', name='get_tasks'),
    url(r'^check_as_done/', 'check_as_done', name='check_as_done'),
    url(r'^check_as_postpone/', 'check_as_postpone', name='check_as_postpone'),
)

src/gym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
import forms_builder.forms.urls

from gym import settings

urlpatterns = [
                  url(r'^', include('main.urls', namespace="main")),
                  url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                  url(r'^members/', include('members.urls', namespace="members")),
                  url(r'^memberships/', include('memberships.urls', namespace="memberships")),
                  url(r'^diary/', include('diary.urls', namespace="diary")),
                  url(r'^store/', include('store.urls', namespace="store")),
                  url(r'^calendar/', include('fullcalendar.urls', namespace="calendar")),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^forms/', include(forms_builder.forms.urls)),
                  url(r'^qualification/', include('qualification.urls', namespace='qualification'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'main.views.custom_403'

src/main/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('main.views',
    url(r'^$', "home", name="home"),
    url(r'^panel/$', 'dashboard', name='dashboard'),
    url(r'^attendances/$', 'attendances', name='attendances'),
    url(r'^report-person-added/$', 'report_person_added', name='report_person_added'),
    url(r'^report-performance/$', 'report_performance', name='report_performance'),
    url(r'^report-members/$', 'report_members', name='report_members'),
    url(r'^report-members-json/$', 'report_members_json', name='report_members_json'),
    url(r'^report_memberships/$', 'report_memberships', name='report_memberships'),
    url(r'^report-memberships-json/$', 'report_memberships_json', name='report_memberships_json'),
    url(r'^report-memberships-sold/$', 'report_memberships_sold', name='report_memberships_sold'),
    url(r'^report-memberships-sold-json/$', 'report_memberships_sold_json', name='report_memberships_sold_json'),

    url(r'^report-memberships-sold-by-seller/$', 'report_memberships_sold_by_seller', name='report_memberships_sold_by_seller'),
    url(r'^report-memberships-sold-by-seller-json/$', 'report_memberships_sold_by_seller_json', name='report_memberships_sold_by_seller_json'),
    url(r'^report-memberships-sold-by-seller-export/$', 'report_memberships_sold_by_seller_export', name='report_memberships_sold_by_seller_export'),

    url(r'^report_attendees/$', 'report_attendees', name='report_attendees'),
    url(r'^report-attendees-json/$', 'report_attendees_json', name='report_attendees_json'),
    url(r'^report-absentees/$', 'report_absentees', name='report_absentees'),
    url(r'^report-absentees-json/$', 'report_absentees_json', name='report_absentees_json'),
    url(r'^report-sales/$', 'report_sales', name='report_sales'),
    url(r'^report-sales-json/$', 'report_sales_json', name='report_sales_json'),
    url(r'^report-sales-graphic/$', 'report_sales_graphic', name='report_sales_graphic'),



    url(r'^install/$', 'install', name='install'),
)

src/members/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('members.views',
    url(r'^home/', "home", name="home"),
    url(r'^members_json/', "members_json", name="members_json"),
    url(r'^prospectus/', "prospectus", name="prospectus"),
    url(r'^prospectus_json/', "prospectus_json", name="prospectus_json"),
    url(r'^search/', "search", name="search"),
    url(r'^last-10-to-enter/', "last_10_to_enter", name="last_10_to_enter"),

    # url(r'^prospectus/', "prospectus", name="prospectus"),

     url(r'^new/', "new", name="new"),
     url(r'^edit/(?P<id>\d+)/$', 'edit', name='edit'),
     url(r'^delete/(?P<id>\d+)/$', 'delete', name='delete'),
     url(r'^add_membership/(?P<person_id>\d+)/$', 'add_membership', name='add_membership'),
     url(r'^edit_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'edit_membership', name='edit_membership'),
     url(r'^freeze_membership/(?P<person_id>\d+)/(?P<person_membership_id>\d+)/$', 'freeze_membership', name='freeze_membership'),
     url(r'^delete_freeze_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'delete_freeze_membership', name='delete_freeze_membership'),
     url(r'^delete_membership/(?P<person_id>\d+)/(?P<id>\d+)/$', 'delete_membership', name='delete_membership'),
     url(r'^add_prospectus/(?P<person_id>\d+)/$', 'add_prospectus', name='add_prospectus'),
     url(r'^contract/(?P<person_membership_id>\d+)/$', 'contract', name='contract'),
     url(r'^details/(?P<person_id>\d+)/$', 'person_details', name='person_details'),
     url(r'^add-attendance/(?P<person_id>\d+)/$', 'add_attendance', name='add_attendance'),
     url(r'^add-exercise/', 'add_exercise', name='add_exercise'),
     url(r'^edit-voucher/(?P<person_membership_id>\d+)/$', 'edit_voucher', name='edit_voucher'),
     url(r'^members-json/', "get_members", name="get_members"),

)

src/main/views.py
import datetime
from functools import reduce
import json
import operator
import xlwt

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import connection
from django.db.models import Count, Max
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.text import slugify
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

from accounts.functions import get_users_of_seller_group, get_member_group, get_seller_group
from gym import settings
from main.functions import date_handler, get_event
from main.models import Attendance, Prospectus, PersonMembership, Person, Membership, MONTHS, YEARS
from members.functions import get_prospectus, get_contract
from store.models import TypeVoucherProduct


def home(request):
    hide_nav = True
    hide_footer = True
    title = 'AtixPlus'
    home_background = settings.HOME_BACKGROUND
    return render(request, "main/home.html", locals())


@login_required
def dashboard(request):
    title = "Panel de control"

    today = datetime.date.today()
    today_min = datetime.datetime.combine(today, datetime.time.min)
    today_max = datetime.datetime.combine(today, datetime.time.max)

    person_count = Person.objects.all().count()
    person_count_today = Person.objects.filter(created_at__range=(today_min, today_max)).count()

    prospectus = Prospectus.objects.filter(created_at__range=(today_min, today_max))
    prospectus_today_count = prospectus.count()
    prospectus_today_count_close_sale = prospectus.filter(close_sale=True).count()

    start_week = today - datetime.timedelta(today.weekday())
    end_week = start_week + datetime.timedelta(7)
    prospectus = Prospectus.objects.filter(created_at__range=(start_week, end_week))
    prospectus_week_count = prospectus.count()
    prospectus_week_count_close_sale = prospectus.filter(close_sale=True).count()

    prospectus = Prospectus.objects.filter(created_at__month=today.month)
    prospectus_month_count = prospectus.count()
    prospectus_month_count_close_sale = prospectus.filter(close_sale=True).count()

    person_memberships = PersonMembership.objects.values('membership__id', 'membership__product__name').filter(
        active=True).annotate(Count('membership'))

    for person_membership in person_memberships:
        id_ = person_membership['membership__id']
        person_membership['today_count'] = PersonMembership.objects.filter(membership__id=id_, created_at__range=(
            today_min, today_max)).count()
        person_membership['week_count'] = PersonMembership.objects.filter(membership__id=id_, created_at__range=(
            start_week, end_week)).count()
        person_membership['month_count'] = PersonMembership.objects.filter(membership__id=id_,
                                                                           created_at__month=today.month).count()

    attendances_count = Attendance.objects.all().count()
    attendances_today_count = Attendance.objects.filter(created_at__range=(today_min, today_max)).count()
    attendances_week_count = Attendance.objects.filter(created_at__range=(start_week, end_week)).count()
    attendances_month_count = Attendance.objects.filter(created_at__month=today.month).count()

    membership_spent_count = PersonMembership.objects.all().count()
    membership_spent_count_today = PersonMembership.objects.filter(created_at__range=(today_min, today_max)).count()
    return render(request, "main/dashboard.html", locals())


def custom_403(request):
    return render(request, "main/403.html")


def date_hour(timestamp):
    return datetime.datetime.fromtimestamp(timestamp).strftime("%x H")


@login_required
def attendances(request):
    from django.utils.timezone import activate
    activate(settings.TIME_ZONE)
    # http://test2.triait.com/question/Hourly-grouping-of-rows-using-Django/

    labels = []
    series = []

    truncate_date = connection.ops.date_trunc_sql('month', 'created_at')
    qs = Attendance.objects.extra({'month': truncate_date})
    report = qs.values('month').annotate(Count('pk')).order_by('month')

    for r in report:
        date = datetime.datetime.strptime(r['month'], "%Y-%m-%d").date()
        labels.append(str(date.month) + '-' + str(date.year))

    hours_in_time = {}
    for x in range(24):
        # if x < 10:
        #     hours_in_time['0' + str(x)] = []
        # else:
        #     hours_in_time[str(x)] = []
        # hours_in_time[str(x)] = []
        hours_in_time[x] = []

    for hour_in_time in hours_in_time:
        series.append(hour_in_time)
        for r in report:
            year_month = str(r['month']).replace('-01', '', 1)  # 2014-09
            # if len(year_month) > 7:
            #     year_month = year_month.

            data = {'year_month': year_month, 'count': '0'}
            hours_in_time[hour_in_time].append(data)

    hours_in_month = Attendance.objects.extra(
        {'year': 'strftime("%%Y", created_at)', 'month': 'strftime("%%m", created_at)',
         'hour': 'strftime("%%H", created_at)'}, where=["created_at != %s"], params=["null"]) \
        .order_by('year', 'month', 'hour').values('year', 'month', 'hour').annotate(
        count=Count('id'))

    for t in hours_in_month:
        current_hour = int(t['hour'])
        current_month = str(t['month'])
        current_year = str(t['year'])
        current_count = str(t['count'])

        year_month_current = current_year + '-' + current_month
        data = {'year_month': year_month_current, 'count': current_count,}

        for idx, item in enumerate(hours_in_time[current_hour]):
            if year_month_current == item['year_month']:
                hours_in_time[current_hour][idx] = data
                break

        print(current_year + ' - ' + current_month + ' - ' + str(current_hour) + 'h. - ' + current_count)

    return render(request, "main/attendances_tmp2.html", locals())


@login_required
@permission_required('main.report_added_people_by_users')
def report_person_added(request):
    title = _('prospectus created')
    truncate_date = connection.ops.date_trunc_sql('day', 'created_at')
    qs = Person.objects.extra({'month': truncate_date})
    report = qs.values('created_by__first_name', 'month').order_by('-created_at').annotate(
        cregister=Count('created_by'), cmonth=Count('created_at'))

    data = {}
    keys = {'date'}

    for r in report:
        date = r['month']
        name = r['created_by__first_name']
        if name == '':
            name = "Unnamed"
        mount = r['cregister']
        data.setdefault(date, {})['date'] = date
        data.setdefault(date, {})[name] = mount
        keys.add(name)

    objts = []

    for i in sorted(data):
        objts.append(data[i])

    return render(request, 'main/report_person_added.html', locals())


@login_required
@permission_required('accounts.view_summary_members')
def report_members(request):
    title = _('members report')
    columns_title = ['person_id', _('DNI'), _('name'), _('surname'), _('email'), _('birthday'), _('sex'),
                     _('cellphone'),
                     _('created'), _('by'), _('membership'), _('end'), 'total_memberships']
    columns_data = ['person__id', 'person__dni', 'person__name', 'person__surname', 'person__email', 'person__birthday',
                    'person__sex', 'person__cellphone', 'person__created_at', 'person__created_by__first_name',
                    'membership_name', 'to',
                    'count_ids']

    columns_non_orderable = ['membership_name', 'to', 'count_ids']
    columns_hidden = ['person__id']

    show_range_fields = True
    show_timepicker = False
    filter_to_show_range_fields = ['_in_range_birthday', '_with_membership_expired_in_range_dates']
    sellers = get_users_of_seller_group()

    filter_options = [
        ('_all', _('with out specification')),
        ('_in_range_birthday', _('with birthday in range')),
        ('_with_membership_activated', _('with membership actived')),
        ('_without_membership_activated', _('without membership actived')),
        ('_with_membership_to_expire_in_next_7_days', _('with membership to expire in next 7 days')),
        ('_with_membership_expired_in_last_7_days', _('with membership to expired in last 7 days')),
        ('_with_membership_expired_in_range_dates', _('with membership expired in range dates')),
    ]
    json_service = reverse('main:report_members_json')
    return render(request, 'main/layout_report_by_user.html', locals())


@csrf_exempt
@login_required()
def report_members_json(request):
    end, field_order_by, query, start, range_since, range_to = get_datatable_data(request,
                                                                                  date_format=settings.DATE_FORMAT)

    people = PersonMembership.objects.values('person__id', 'person__dni', 'person__name', 'person__surname',
                                             'person__email',
                                             'person__birthday', 'person__sex', 'person__cellphone',
                                             'person__created_at', 'person__created_by__first_name').annotate(
        count_ids=Count('person'))

    by_user = request.POST.get('byUser')
    if by_user:
        people = people.filter(person__created_by__id=by_user)

    today = datetime.datetime.today()
    if query == '_in_range_birthday':

        # Build the list of month/day tuples.
        monthdays = [(range_since.month, range_since.day)]
        while range_since <= range_to:
            monthdays.append((range_since.month, range_since.day))
            range_since += datetime.timedelta(days=1)

        # Tranform each into queryset keyword args.
        monthdays = (dict(zip(("person__birthday__month", "person__birthday__day"), t))

src/main/templates/main/attendances.html
{% extends 'main/base_container.html' %}

{% load static %}
{% load main_extras %}
{% block content %}
    <div style="width:100%">
        <div>
            <canvas id="canvas" height="350" width="900"></canvas>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div style="width:100%">
        <div>
            <canvas id="canvas2" height="350" width="900"></canvas>
        </div>
    </div>
{% endblock %}
{% block footer_scripts %}
    <script src="{% static 'main/js/Chart.js' %}"></script>
    <script>

        var labels = [];
        var data = [];
        {% for r in report %}
            labels.push('{{ r.month|to_date|date:'M-Y' }}');
            data.push({{ r.pk__count }});{% endfor %}

        var lineChartData = {
            labels: labels,
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: data
                }
            ]

        };


        {% for hour_in_time in hours_in_time %}
{#            {% if hour_in_time == '00' or hour_in_time == '01' %}#}
            var data{{ hour_in_time }} = {{ hours_in_time|to_js:hour_in_time }};
{#            {% endif %}#}
        {% endfor %}

        var lineChartData2 = {
            labels: labels,
            datasets: [
                {% for hour_in_time in hours_in_time %}
{#                    {% if hour_in_time == '00' or hour_in_time == '01' %}#}
                    {
                        label: "hora {{ hour_in_time }}",
                        fillColor: "rgba(220,220,220,0.2)",
                        strokeColor: "rgba(220,220,220,1)",
                        pointColor: "rgba(220,220,220,1)",
                        pointStrokeColor: "#fff",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(220,220,220,1)",
                        data: data{{ hour_in_time }}
                    }
                    {% if not forloop.last %},{% endif %}
{#                    {% endif %}#}
                {% endfor %}
            ]
        };

        window.onload = function () {

            var ctx = document.getElementById("canvas").getContext("2d");
            window.myLine = new Chart(ctx).Line(lineChartData, {
                responsive: true
            });

            var ctx2 = document.getElementById("canvas2").getContext("2d");
            window.myLine = new Chart(ctx2).Line(lineChartData2, {
                responsive: true,
                legendTemplate : "<ul class='te-legend'>"
                +"<li><span></span>0</li>"
                +"<li><span></span>1</li>"
                +"<li><span></span>2</li>"
                +"<li><span></span>3</li>"
                +"<li><span></span>4</li>"
                +"<li><span></span>5</li>"
                +"<li><span></span>6</li>"
                +"<li><span></span>7</li>"
                +"<li><span></span>8</li>"
                +"<li><span></span>9</li>"
                +"<li><span></span>10</li>"
                +"<li><span></span>11</li>"
                +"<li><span></span>12</li>"
                +"<li><span></span>13</li>"
                +"<li><span></span>14</li>"
                +"<li><span></span>15</li>"
                +"<li><span></span>16</li>"
                +"<li><span></span>17</li>"
                +"<li><span></span>18</li>"
                +"<li><span></span>19</li>"
                +"<li><span></span>20</li>"
                +"<li><span></span>21</li>"
                +"<li><span></span>22</li>"
                +"<li><span></span>23</li></ul>"
            });
        }


    </script>
{% endblock %}

src/main/templates/main/attendances_tmp.html
{% extends 'main/base_container.html' %}

{% load static %}
{% load main_extras %}
{% block content %}
    <div ng-controller="LineCtrl" style="width:100%">
        {#        <canvas id="bar" class="chart chart-bar" data="data"#}
        {#                labels="labels" legend="true" series="series"#}
        {#                click="onClick">#}
        {#        </canvas>#}

        <canvas id="bar" class="chart chart-bar" data="data"
                labels="labels"></canvas>

    </div>
    <br/>
    <br/>
    <br/>
    <div style="width:100%">
        <div>
            <canvas id="canvas" height="450" width="600"></canvas>
        </div>
    </div>
{% endblock %}
{% block footer_scripts %}
    <link href="{% static 'main/angular/chart/angular-chart.css' %}">


    <script src="{% static 'main/angular/angular.min.js' %}"></script>
    <script src="http://jtblin.github.io/angular-chart.js/bower_components/Chart.js/Chart.min.js"></script>
    <script src="{% static 'main/angular/chart/angular-chart.js' %}"></script>

    <script src="{% static 'main/angular/app_lines.js' %}"></script>

    <script>
        var data = [];
        {% for hour_in_time in hours_in_time %}
            data.push({{ hours_in_time|to_js:hour_in_time }});
        {% endfor %}


        var barChartData = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [
                {
                    fillColor: "rgba(220,220,220,0.5)",
                    strokeColor: "rgba(220,220,220,1)",
                    data: [65, 59, 90, 81, 56, 55, 40]
                },
                {
                    fillColor: "rgba(151,187,205,0.5)",
                    strokeColor: "rgba(151,187,205,1)",
                    data: [28, 48, 40, 19, 96, 27, 100]
                },
                {
                    fillColor: "rgba(51,87,255,0.5)",
                    strokeColor: "rgba(51,87,255,1)",
                    data: [42, 12, 10, 36, 15, 27, 21]
                }
            ]
        }
        {#        var myLine = new Chart(document.getElementById("canvas").getContext("2d")).StackedBar(barChartData);#}

    </script>
{% endblock %}

src/main/templates/main/attendances_tmp2.html
{% extends 'main/base_container.html' %}

{% load static %}
{% load main_extras %}
{% block content %}
    <div style="width: 80%">
        <div id="chart"></div>
    </div>
{% endblock %}
{% block footer_scripts %}
    <link href="{% static 'main/c3/c3.css' %}" rel="stylesheet" type="text/css">

    <!-- Load d3.js and c3.js -->
    {#    <script src="{% static 'main/d3.v3.min.js' %}" charset="utf-8"></script>#}
    <!--<script src="{% static 'main/c3/d3.min.js' %}" type="text/javascript"></script>-->
    <script src="{% static 'main/c3/c3.js' %}" type="text/javascript"></script>

    <script>


        var chart = c3.generate({
            bindto: '#chart',
            data: {
                columns: [{% for hour_in_time in hours_in_time %}{% if hour_in_time > 7 and hour_in_time < 20 %}
                    ['{{ hour_in_time }}', {{ hours_in_time|to_js:hour_in_time }}]{% if not forloop.last %}, {% endif %}{% endif %}{% endfor %}
                ],
                type: 'bar',
                groups: [
                    [{% for hour_in_time in hours_in_time %}{% if hour_in_time > 7 and hour_in_time < 20 %}'{{ hour_in_time }}' {% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}]
                ]
            },
            grid: {
                y: {
                    lines: [{value: 0}]
                }
            }
        });

        {#        setTimeout(function () {#}
        {#            chart.groups([['data1', 'data2', 'data3']])#}
        {#        }, 1000);#}
        {##}
        {#        setTimeout(function () {#}
        {#            chart.load({#}
        {#                columns: [['data4', 100, -50, 150, 200, -300, -100]]#}
        {#            });#}
        {#        }, 1500);#}
        {##}
        {#        setTimeout(function () {#}
        {#            chart.groups([['data1', 'data2', 'data3', 'data4']])#}
        {#        }, 2000);#}

    </script>
{% endblock %}

src/main/templates/main/base_form.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% load main_extras %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        {% include 'hock/form.html' %}
    </div>
</div>
{% endblock %}

src/main/templates/main/home.html
{% extends 'main/base.html' %}

{% load static %}

{% block outer_content %}

    <div class="hero" {% if home_background != '' %} style="background-image: url('{{ home_background }}')"{% endif %}>
        <div class="hero-menu">
            {% if user.is_authenticated %}
                <a href="{% url 'main:dashboard' %}">Ir a panel</a> | <a href="{% url 'accounts:logout' %}">Salir</a>
            {% else %}
                <a href="{% url 'accounts:login' %}">Ingresar</a>
            {% endif %}
        </div>
        <div class="hero-inner">
            <img src="{% static 'main/img/logo/fitgram_logo.png' %}" alt="Logo Image">

            <div class="hero-copy">
                <h1>Fitgram</h1>

                <p>planeamiento y seguimiento para gimnasios</p>
            </div>
        </div>
    </div>
{% endblock %}

src/main/templates/main/navigation.html
{% load static %}
{% load i18n %}
{% load main_extras %}

<header class="navigation" role="banner">
    <div class="navigation-wrapper">
        <a href="{% url 'main:dashboard' %}" class="logo">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
        </a>
        <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>

        {% if user.is_authenticated %}
            <nav role="navigation">
                <ul id="js-navigation-menu" class="navigation-menu show">
                    {% if perms.accounts.view_members %}
                        <li class="nav-link"><a href="{% url 'members:home' %}">{% trans 'people' %}</a></li>
                    {% endif %}
                    {% if perms.accounts.view_members %}
{#                        <li class="nav-link"><a href="{% url 'members:prospectus' %}">{% trans 'prospectus' %}</a></li>#}
                    {% endif %}
                    {% if perms.main.view_memberships %}
                        <li class="nav-link"><a href="{% url 'memberships:home' %}">{% trans 'memberships' %}</a></li>
                    {% endif %}
                    {% if perms.accounts.view_members %}
                        <li class="nav-link"><a href="{% url 'diary:tasks_todo' %}">{% trans 'tasks' %}</a></li>
                    {% endif %}
                    {% if perms.main.view_cashbox %}
                        <li class="nav-link"><a href="javascript:void(0)">{% trans 'sales' %}</a></li>
                    {% endif %}
                    {#                    <li class="nav-link"><a href="{% url 'accounts:list' %}">Personal</a></li>#}

                    <li class="nav-link more"><a href="javascript:void(0)">reports</a>
                        <ul class="submenu">
                            <li><a href="{% url 'main:attendances' %}">{% trans 'Attendances' %}</a></li>
                            <li><a href="javascript:void(0)">{% trans 'Sales' %}</a></li>
                            <li><a href="{% url 'main:report_person_added' %}">{% trans 'Person Added' %}</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        {% endif %}


        <div class="navigation-tools">
            <ul id="js-navigation-menu" class="navigation-menu show">
                {# <li class="nav-link"><a href="{% url 'main:contact_us' %}">Contáctanos</a></li> #}


                {% if user.is_authenticated %}
                    <li class="nav-link more"><a href="javascript:void(0)">{% trans 'welcome' %} &nbsp;
                        <strong>{{ user.get_full_name }} {{ user|primary_group }}</strong></a>
                        <ul class="submenu">
                            <li class="nav-link"><a href="{% url 'accounts:logout' %}">{% trans 'close session' %}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-link"><a href="{% url 'accounts:login' %}">{% trans 'login' %}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>