src/gym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
import forms_builder.forms.urls

from gym import settings

urlpatterns = [
                  url(r'^', include('main.urls', namespace="main")),
                  url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                  url(r'^members/', include('members.urls', namespace="members")),
                  url(r'^memberships/', include('memberships.urls', namespace="memberships")),
                  url(r'^diary/', include('diary.urls', namespace="diary")),
                  url(r'^store/', include('store.urls', namespace="store")),
                  url(r'^calendar/', include('fullcalendar.urls', namespace="calendar")),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^forms/', include(forms_builder.forms.urls)),
                  url(r'^qualification/', include('qualification.urls', namespace='qualification'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'main.views.custom_403'

src/store/urls.py
__author__ = 'jona'

from django.conf.urls import url, patterns

urlpatterns = patterns('store.views',
                       url(r'^$', "home", name="home"),
                       url(r'^products/', "products", name="products"),
                       url(r'^products-json/', "get_products", name="get_products"),
                       url(r'^product/new/$', "new_product", name="new_product"),
                       url(r'^product/edit/(?P<product_id>\d+)/$', "edit_product", name="edit_product"),
                       url(r'^product/delete/$', "delete_product", name="delete_product"),
                       url(r'^product/convert/(?P<product_id>\d+)/$', "convert_product", name="convert_product"),
                       url(r'^category/new/', "new_category", name="new_category"),
                       url(r'^category/edit/', "edit_category", name="edit_category"),
                       url(r'^category/delete/', "delete_category", name="delete_category"),
                       url(r'^categories/', "categories", name="categories"),
                       url(r'^settings/$', "settings_route", name="settings"),
                       url(r'^settings/type-voucher/new/', "new_type_voucher", name="new_type_voucher"),
                       url(r'^settings/type-voucher/delete/', "delete_type_voucher", name="delete_type_voucher"),
                       url(r'^settings/type-voucher/edit/', "edit_type_voucher", name="edit_type_voucher"),
                       url(r'^settings/company-type-voucher/new/', "new_company_type_voucher", name="new_company_type_voucher"),
                       url(r'^settings/company-type-voucher/delete/', "delete_company_type_voucher", name="delete_company_type_voucher"),
                       url(r'^settings/company-type-voucher/edit/', "edit_company_type_voucher", name="edit_company_type_voucher"),
                       url(r'^inventory/$', "inventory", name="inventory"),
                       url(r'^incoming/$', "incoming", name="incoming"),
                       url(r'^incoming/report-json/$', "incoming_report_json", name="incoming_report_json"),
                       url(r'^incoming/new/$', "new_incoming", name="new_incoming"),
                       url(r'^expenses/$', "expenses", name="expenses"),
                       url(r'^expenses/report-json/$', "expenses_report_json", name="expenses_report_json"),
                       url(r'^expenses/new/$', "new_expenses", name="new_expenses"),
                       url(r'^voucher/view/(?P<voucher_id>\d+)/$', "voucher_view", name="voucher_view"),
                       url(r'^voucher/new/save/$', "save_voucher", name="save_voucher"),
                       url(r'^voucher/search-client/$', "search_client", name="search_client"),
                       url(r'^voucher/add-product/$', "add_product", name="add_product"),
                       url(r'^voucher/del-product/$', "del_product", name="del_product"),
                       url(r'^voucher/create-header/$', "create_header", name="create_header"),
                       url(r'^voucher/edit/$', "edit_voucher", name="edit_voucher"),
                       url(r'^voucher/pay/(?P<voucher_id>\d+)/$', "pay_voucher", name="pay_voucher"),
                       )

src/store/views.py
from decimal import Decimal
import datetime
import json

from django.contrib.auth.decorators import login_required, permission_required
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, Sum
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.db import connection

from django.views.decorators.csrf import csrf_exempt

from accounts.models import Person
from main.functions import date_handler, monthdelta
from main.models import PersonMembership
from main.views import get_datatable_data
from store.forms import ProductForm, CategoryProductForm, \
    TypeVoucherProductForm, CompanyTypeVoucherForm
from store.functions import get_customer, get_provider, get_objective, generate_inventory, insert_register_inventory
from store.models import VoucherProductDetails, Product, CategoryProduct, TypeVoucherProduct, Customer, Company, \
    VoucherProduct, Inventory, Card, CompanyTypeVoucher
from gym import settings


@login_required
@permission_required('store.view_cashbox')
def home(request):
    return render(request, "store/home.html", locals())


@login_required
@permission_required('store.view_cashbox')
def new_incoming(request):
    voucher = "incoming"
    voucher_types = TypeVoucherProduct.objects.filter(is_deleted=False)
    date_start = datetime.date(datetime.date.today().year, datetime.date.today().month, 1)
    date_end = monthdelta(date_start, 1)
    date_end = date_end - datetime.timedelta(days=1)
    my_companies = get_vouchers_x_companies(date_start, date_end)
    return render(request, "store/form.html", locals())


@login_required
@permission_required('store.view_cashbox')
def incoming(request):
    title = _('incoming')
    button = {
        'text': _('new') + " " + _('incoming'),
        'route': reverse('store:new_incoming')
    }
    columns_title = [_('series'), _('voucher'), _('date'), _('person'), _('company'), _('total'), _('cash'), _('card'),
                     _('amount card'), _('status')]
    columns_data = ['series_number', 'type_voucher_product__name', 'date_issue', 'person_name',
                    'customer__company__name', 'total_cashed', 'form_pay_cash_amount', 'form_pay_card_type__name',
                    'form_pay_card_amount', 'status']

    show_range_fields = True
    show_timepicker = True
    sum_colums = [5, 6, 8]
    total_column = min(sum_colums)
    number_colums = len(columns_title) - total_column
    range_cols = range(0, number_colums)
    filter_to_show_range_fields = ['_in_range_dates']
    filter_options = [
        ('_all', _('all')),
        ('_today', _('today')),
        ('_yesterday', _('yesterday')),
        ('_this_week', _('this week')),
        ('_in_range_dates', _('in range dates'))
    ]
    json_service = reverse('store:incoming_report_json')
    return render(request, 'main/layout_report.html', locals())


@csrf_exempt
@login_required()
def incoming_report_json(request):
    end, field_order_by, query, start, range_since, range_to = get_datatable_data(request)

    rows = VoucherProduct.objects \
        .extra(select={
        'person_name': '"accounts_person"."name"||\', \'||"accounts_person"."surname"',
        'series_number': '"store_voucherproduct"."series"||\'-\'||"store_voucherproduct"."number"'
    }) \
        .values('id',
                'series_number',
                'type_voucher_product__name',
                'date_issue',
                'status',
                'customer__company__name',
                'customer__person__name',
                'person_name',
                'total_cashed',
                'form_pay_cash_amount',
                'form_pay_card_type__name',
                'form_pay_card_amount') \
        .filter(is_input=True, is_deleted=False)

    today = datetime.datetime.today()

    if query == '_in_range_dates':
        rows = rows.filter(created_at__range=(range_since, range_to))
    elif query == '_today':
        today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
        today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
        rows = rows.filter(date_issue__range=(today_min, today_max))
    elif query == '_yesterday':
        day = datetime.date.today() - datetime.timedelta(1)
        day_min = datetime.datetime.combine(day, datetime.time.min)
        day_max = datetime.datetime.combine(day, datetime.time.max)
        rows = rows.filter(date_issue__range=(day_min, day_max))
    elif query == '_this_week':
        day = datetime.date.today() - datetime.timedelta(7)
        day_min = datetime.datetime.combine(day, datetime.time.min)
        rows = rows.filter(date_issue__range=(day_min, datetime.datetime.today()))

    rows = rows.order_by(field_order_by)

    iTotalDisplayRecords = rows.count()

    if end:
        rows = rows[start:end]

    for row in rows:
        row['status'] = VoucherProduct.STATUS_VOUCHER[row['status'] - 1][1]
        row['series_number'] = '<a href="' + reverse('store:voucher_view', args=[row['id']]) + '">' + (
            row['series_number'] if row['series_number'] is not None else "0000-0000000") + '</a>'

    result = {}
    result['data'] = list(rows)
    result['iTotalRecords'] = rows.count()
    result['iTotalDisplayRecords'] = iTotalDisplayRecords

    return HttpResponse(json.dumps(result, default=date_handler), content_type='application/json')


@login_required
@permission_required('store.view_cashbox')
def expenses(request):
    title = _('expenses')
    button = {
        'text': _('new') + " " + _('expenses'),
        'route': reverse('store:new_expenses')
    }
    columns_title = [_('series'), _('voucher'), _('date'), _('person'), _('company'), _('total'), _('cash'), _('card'),
                     _('amount card'), _('status')]
    columns_data = ['series_number', 'type_voucher_product__name', 'date_issue', 'person_name',
                    'customer__company__name', 'total_cashed', 'form_pay_cash_amount', 'form_pay_card_type__name',
                    'form_pay_card_amount', 'status']

    show_range_fields = True
    show_timepicker = True
    sum_colums = [5, 7]
    total_column = min(sum_colums)
    number_colums = len(columns_title) - total_column
    range_cols = range(0, number_colums)
    filter_to_show_range_fields = ['_in_range_dates']
    filter_options = [
        ('_all', _('all')),
        ('_today', _('today')),
        ('_yesterday', _('yesterday')),
        ('_this_week', _('this week')),
        ('_in_range_dates', _('in range dates'))
    ]
    json_service = reverse('store:expenses_report_json')
    return render(request, 'main/layout_report.html', locals())


@csrf_exempt
@login_required()
def expenses_report_json(request):
    end, field_order_by, query, start, range_since, range_to = get_datatable_data(request,
                                                                                  date_format=settings.DATE_FORMAT)

    rows = VoucherProduct.objects \
        .extra(select={
        'person_name': '"accounts_person"."name"||\', \'||"accounts_person"."surname"',
        'series_number': '"store_voucherproduct"."series"||\'-\'||"store_voucherproduct"."number"'
    }) \
        .values('id',
                'series_number',
                'type_voucher_product__name',
                'status',
                'date_issue',
                'person_name',
                'provider__company__name',
                'provider__person__name',
                'total_cashed',
                'form_pay_cash_amount',
                'form_pay_card_type__name',
                'form_pay_card_amount') \
        .filter(is_input=False, is_deleted=False)

    today = datetime.datetime.today()

    if query == '_in_range_dates':
        rows = rows.filter(created_at__range=(range_since, range_to))
    elif query == '_today':
        today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
        today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
        rows = rows.filter(date_issue__range=(today_min, today_max))
    elif query == '_yesterday':
        day = datetime.date.today() - datetime.timedelta(1)
        day_min = datetime.datetime.combine(day, datetime.time.min)
        day_max = datetime.datetime.combine(day, datetime.time.max)
        rows = rows.filter(date_issue__range=(day_min, day_max))
    elif query == '_this_week':
        day = datetime.date.today() - datetime.timedelta(7)
        day_min = datetime.datetime.combine(day, datetime.time.min)
        rows = rows.filter(date_issue__range=(day_min, datetime.datetime.today()))
    rows = rows.order_by(field_order_by)

    iTotalDisplayRecords = rows.count()

    if end:
        rows = rows[start:end]
    for row in rows:
        row['status'] = VoucherProduct.STATUS_VOUCHER[row['status'] - 1][1]
        row['series_number'] = '<a href="' + reverse('store:voucher_view', args=[row['id']]) + '">' + (
            row['series_number'] if row['series_number'] is not None else "0000-0000000") + '</a>'

    result = {}
    result['data'] = list(rows)
    result['iTotalRecords'] = rows.count()
    result['iTotalDisplayRecords'] = iTotalDisplayRecords

    return HttpResponse(json.dumps(result, default=date_handler), content_type='application/json')


@login_required
@permission_required('store.view_cashbox')
def new_expenses(request):
    voucher = _("expenses")
    voucher_types = TypeVoucherProduct.objects.filter(is_deleted=False)
    date_start = datetime.date(datetime.date.today().year, datetime.date.today().month, 1)
    date_end = monthdelta(date_start, 1)
    date_end = date_end - datetime.timedelta(days=1)
    my_companies = get_vouchers_x_companies(date_start, date_end)

    return render(request, "store/form.html", locals())

src/store/templates/store/home.html
{% extends 'main/layout.html' %}

{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>

{% endblock %}

src/store/templates/store/inventory.html
{% extends 'main/layout.html' %}

{% load i18n %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'main/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css' %}"/>
{% endblock %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'store:inventory' %}">{% trans title|capfirst %}</a>
    </li>
{% endblock %}

{% block page_toolbar %}
    <a href="{% url 'store:new_product' %}" class="btn blue pull-right btn-fit-height">
        <i class="fa fa-plus"></i>
        {% trans 'new product'|capfirst %}
    </a>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-globe"></i>{% trans 'products'|capfirst %}
                    </div>
                    <div class="tools">
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="inventory">
                    <thead>
                    <tr>
                        <th>
                            {% trans 'product'|capfirst %}
                        </th>
                        <th>
                            {% trans 'voucher'|capfirst %}
                        </th>
                        <th>
                            {% trans 'observation'|capfirst %}
                        </th>
                        <th>
                            {% trans 'amount'|capfirst %}
                        </th>
                        <th>
                            {% trans 'unitary price'|capfirst %}
                        </th>
                        <th>
                            {% trans 'type'|capfirst %}
                        </th>
                        <th>
                            {% trans 'balance amount'|capfirst %}
                        </th>
                        <th>
                            {% trans 'balance price'|capfirst %}
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    {% if inventory %}
                    {% for register in inventory %}
                    <tr>
                        <td>{{ register.product.name }}</td>
                        <td>{{ register.voucher_product.series }}-{{ register.voucher_product.number }}</td>
                        <td>{{ register.observation }}</td>
                        {% if register.input_amount == 0 %}
                            <td>{{ register.output_amount }}</td>
                            <td>{{ register.output_unitary_price }}</td>
                            <td>
                                 <a href="javascript:;" class="btn default btn-xs red-flamingo">
                                    <i class="glyphicon glyphicon-log-out"></i>
                                    {% trans 'Output' %}
                                </a>
                            </td>
                        {% else %}
                            <td>{{ register.input_amount }}</td>
                            <td>{{ register.input_unitary_price }}</td>
                            <td>
                                <a href="javascript:;" class="btn default btn-xs green-jungle">
                                    <i class="glyphicon glyphicon-log-in"></i>
                                    {% trans 'Input' %}
                                </a>
                            </td>
                        {% endif %}
                        <td>{{ register.balance_amount }}</td>
                        <td>{{ register.balance_unitary_price }}</td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts_plugins %}
<script type="text/javascript" src="{% static 'main/plugins/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js' %}"></script>
{% endblock %}

{% block scripts %}
        var table = $('#inventory');

        /* Table tools samples: https://www.datatables.net/release-datatables/extras/TableTools/ */

        /* Set tabletools buttons and button container */

        $.extend(true, $.fn.DataTable.TableTools.classes, {
            "container": "btn-group tabletools-dropdown-on-portlet",
            "buttons": {
                "normal": "btn btn-sm default",
                "disabled": "btn btn-sm default disabled"
            },
            "collection": {
                "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
            }
        });

        var oTable = table.dataTable({
            "order": [
                [0, 'asc']
            ],
            "lengthMenu": [
                [5, 10, 15, 20, -1],
                [5, 10, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 10,

            "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "tableTools": {
                "sSwfPath": "{% static 'main/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf' %}",
                "aButtons": [{
                    "sExtends": "pdf",
                    "sButtonText": "PDF"
                }, {
                    "sExtends": "csv",
                    "sButtonText": "CSV"
                }, {
                    "sExtends": "xls",
                    "sButtonText": "Excel"
                }, {
                    "sExtends": "print",
                    "sButtonText": "Print",
                    "sInfo": 'Please press "CTR+P" to print or "ESC" to quit',
                    "sMessage": "Generated by DataTables"
                }]
            }
        });
{% endblock %}%}

src/store/templates/store/products.html
{% extends 'main/layout.html' %}

{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'main/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css' %}"/>
{% endblock %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'store:products' %}">{% trans title|capfirst %}</a>
    </li>
{% endblock %}

{% block page_toolbar %}
    <a href="{% url 'store:new_product' %}" class="btn blue pull-right btn-fit-height">
        <i class="fa fa-plus"></i>
        {% trans 'new product'|capfirst %}
    </a>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-globe"></i>{% trans 'products'|capfirst %}
                    </div>
                    <div class="tools">
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="products">
                    <thead>
                    <tr>
                        <th>
                            {% trans 'code'|capfirst %}
                        </th>
                        <th>
                            {% trans 'name'|capfirst %}
                        </th>
                        <th>
                            {% trans 'category'|capfirst %}
                        </th>
                        <th>
                            {% trans 'unid type'|capfirst %}
                        </th>
                        <th>
                            {% trans 'stock'|capfirst %}
                        </th>
                        <th>
                            {% trans 'price'|capfirst %}
                        </th>
                        <th>
                            {% trans 'pack'|capfirst %}
                        </th>
                        <th>
                            {% trans 'units per pack'|capfirst %}
                        </th>
                        <th>

                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if products %}
                    {% for product in products %}
                    <tr id="r{{ product.id }}">
                        <td>{{ product.code }}</td>
                        <td>{{ product.name }}</td>
                        <td>{{ product.category.name }}</td>
                        <td>{{ product.UNITS_TYPE|get_value:product.unit_type }}</td>
                        <td>{{ product.stock }}</td>
                        <td>{{ product.price }}</td>
                        <td>{{ product.reference.name }}</td>
                        <td>{{ product.quantity }}</td>
                        <td>
                            <a href="{% url 'store:edit_product' product.id %}" class="btn default btn-xs black edit">
                                <i class="fa fa-edit"></i> {% trans "edit"|capfirst %}
                            </a>
                            <a href="javascript:;" class="btn default btn-xs black delete-product" data-id="{{ product.id }}">
                                <i class="fa fa-trash-o"></i> {% trans "delete"|capfirst %}
                            </a>
                            {% if product.reference %}
                                {% if product.stock > 0 %}
                                <a href="{% url 'store:convert_product' product.id %}" class="btn default btn-xs black">
                                    <i class="fa fa-trash-o"></i> {% trans "convert"|capfirst %}
                                </a>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                    {% endif %}
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts_plugins %}
<script type="text/javascript" src="{% static 'main/plugins/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js' %}"></script>
{% endblock %}

{% block scripts %}
        var table = $('#products');

        /* Table tools samples: https://www.datatables.net/release-datatables/extras/TableTools/ */

        /* Set tabletools buttons and button container */

        $.extend(true, $.fn.DataTable.TableTools.classes, {
            "container": "btn-group tabletools-dropdown-on-portlet",
            "buttons": {
                "normal": "btn btn-sm default",
                "disabled": "btn btn-sm default disabled"
            },
            "collection": {
                "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
            }
        });

        var oTable = table.dataTable({
            "order": [
                [0, 'asc']
            ],
            "lengthMenu": [
                [5, 10, 15, 20, -1],
                [5, 10, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 10,

            "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "tableTools": {
                "sSwfPath": "{% static 'main/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf' %}",
                "aButtons": [{
                    "sExtends": "pdf",
                    "sButtonText": "PDF"
                }, {
                    "sExtends": "csv",
                    "sButtonText": "CSV"
                }, {
                    "sExtends": "xls",
                    "sButtonText": "Excel"
                }, {
                    "sExtends": "print",
                    "sButtonText": "Print",
                    "sInfo": 'Please press "CTR+P" to print or "ESC" to quit',
                    "sMessage": "Generated by DataTables"
                }]
            }
        });

        $('.delete-product').click(function () {
            var id = $(this).attr('data-id');

            $.ajax({
                url: '{% url 'store:delete_product' %}',
                type: 'post',
                dataType: 'json',
                data: {id: id},
                success: function (response) {
                    if (response.success) {
                        $('#r'+id).remove();
                    }
                }
            });

        });
{% endblock %}