src/gym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
import forms_builder.forms.urls

from gym import settings


urlpatterns = [
    url(r'^', include('main.urls', namespace="main")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^members/', include('members.urls', namespace="members")),
    url(r'^memberships/', include('memberships.urls', namespace="memberships")),
    url(r'^diary/', include('diary.urls', namespace="diary")),
    url(r'^store/', include('store.urls', namespace="store")),
    url(r'^calendar/', include('fullcalendar.urls', namespace="calendar")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forms/', include(forms_builder.forms.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'main.views.custom_403'

src/memberships/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = patterns('memberships.views',
    url(r'^$', "home", name="home"),
    url(r'^new/', "new", name="new"),
    url(r'^edit/(?P<id>\d+)/$', 'edit', name='edit'),
    url(r'^delete/(?P<id>\d+)/$', 'delete', name='delete'),
)

src/main/models.py
from datetime import date, datetime

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Model, Sum
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.utils.translation import ugettext as _
from forms_builder.forms.models import FormEntry

from accounts.models import Person
from store.models import Product, VoucherProduct

DAYS = 1
WEEKS = 2
MONTHS = 3
YEARS = 4
VISITS = 5

DURATION_TYPES = (
    (DAYS, _('Days')),
    (WEEKS, _('Weeks')),
    (MONTHS, _('Months')),
    (YEARS, _('Years')),
    (VISITS, _('Visits')),
)

ANY = 0
ONCE = 1
TWICE = 2
THREE_TIMES = 3

ENTRIES_LIMIT_DAILY = (
    (ANY, _('Any')),
    (ONCE, _('ONCE')),
    (TWICE, _('TWICE')),
    (THREE_TIMES, _('THREE_TIMES')),
)


class Membership(Model):
    product = models.ForeignKey(Product)
    duration_frequency = models.IntegerField(_('time'), null=False, blank=None)
    duration_type = models.IntegerField(_('month,day,year'), choices=DURATION_TYPES, default=MONTHS)
    limit_visits_per_day = models.IntegerField(_('limit visits per day'), choices=ENTRIES_LIMIT_DAILY, default=ANY)
    is_on_monday = models.BooleanField(_('monday'), default=True)
    is_on_tuesday = models.BooleanField(_('tuesday'), default=True)
    is_on_wednesday = models.BooleanField(_('wednesday'), default=True)
    is_on_thursday = models.BooleanField(_('thursday'), default=True)
    is_on_friday = models.BooleanField(_('friday'), default=True)
    is_on_saturday = models.BooleanField(_('saturday'), default=True)
    is_on_sunday = models.BooleanField(_('sunday'), default=True)

    is_active = models.BooleanField(_('is active'), default=True)
    is_promo = models.BooleanField(_('is promo'), default=False)
    date_end = models.DateField(_('end at'), null=True, blank=True)

    # is_limit_time = models.BooleanField(default=False)
    # TODO implement period durant the day

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Membership')
        verbose_name_plural = _('Memberships')
        permissions = (
            ("view_memberships", "Can see existing memberships"),
            ("view_seller_team", "Can see seller team"),
        )

    def __str__(self):
        return self.product.name

    def get_count_members(self):
        return PersonMembership.objects.filter(membership=self).count()

    def allowed_days(self):
        days = ''
        if self.is_on_monday:
            days += 'L '
        if self.is_on_tuesday:
            days += 'M '
        if self.is_on_wednesday:
            days += 'W '
        if self.is_on_thursday:
            days += 'J '
        if self.is_on_friday:
            days += 'V '
        if self.is_on_saturday:
            days += 'S '
        if self.is_on_sunday:
            days += 'D '
        return days


class PersonMembership(Model):
    person = ForeignKey(Person)
    membership = ForeignKey(Membership)
    observation = models.TextField(_('target person'), blank=True, null=True)
    since = models.DateField(_('since'), default=timezone.now, null=False)
    to = models.DateField(_('to'), null=False)
    to_real = models.DateField(_('to'), null=False, default=timezone.now)
    active = models.BooleanField(default=False)
    voucher_product = models.ForeignKey(VoucherProduct, null=True)
    contract_number = models.CharField(max_length=10)

    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, related_name='person_membership_created_by')

    class Meta:
        verbose_name = _('Person Membership')
        verbose_name_plural = _('People Memberships')

        permissions = (
            ("view_who_created_member", "Can see who create a member"),
            ("view_last_10_memberships", "Can view last 10 membership acquired by a  person"),
            ("report_added_people_by_users", "Can see report about person added by users.")
        )


class FrozenPersonMembership(Model):
    number = models.CharField(null=False, blank=False, max_length=20)
    person_membership = ForeignKey(PersonMembership)
    since = models.DateField(_('since'), null=False)
    to = models.DateField(_('to'), null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='frozen_person_membership_created_by')

    class Meta:
        verbose_name = _('Person Membership Frozen')
        verbose_name_plural = _('People Memberships Frozen')


PersonMembership.freezing = property(lambda s: FrozenPersonMembership.objects.filter(person_membership=s))

User.count_sales_in_month = property(
    lambda s: PersonMembership.objects.filter(created_by=s, created_at__year=datetime.today().year,
                                              created_at__month=datetime.today().month).count())

User.total_sales_in_month = property(
    lambda s: PersonMembership.objects.filter(created_by=s, created_at__year=datetime.today().year,
                                              created_at__month=datetime.today().month).aggregate(
        Sum('membership__product__price'))['membership__product__price__sum'])


class Prospectus(Model):
    person = ForeignKey(Person)
    entry = ForeignKey(FormEntry)
    close_sale = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Prospectus')
        verbose_name_plural = _('Prospectus')


class Event(Model):
    key = models.SlugField(max_length=100, null=False, blank=None)
    value = models.CharField(max_length=100, null=False, blank=None)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        permissions = (
            ("views_tasks", "Can view tasks assigned to him"),
        )


class Task(Model):
    event = models.ForeignKey(Event, null=True, blank=True)
    action = models.CharField(max_length=100, null=False, blank=None)
    description = models.TextField(null=True, blank=True)
    duration_frequency = models.IntegerField(null=False, blank=None)
    duration_type = models.IntegerField(choices=DURATION_TYPES, default=1)
    default_done = models.BooleanField(default=False)
    is_preventive = models.BooleanField(default=False)

    active = models.BooleanField(default=True)

    def __str__(self):
        return self.event.value + ", " + self.action

    def natural_key(self):
        return (self.event.value, self.action, self.description)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')


class UserTask(Model):
    task = models.ForeignKey(Task, null=True, blank=True)
    user = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.CharField(_('id'), max_length=200, blank=True, null=True)
    object_repr = models.CharField(_('reference'), max_length=200)
    date = models.DateField()
    date_done = models.DateField(null=True, blank=True)
    date_postpone = models.DateField(null=True, blank=True)
    resume = models.TextField(null=False, blank=True)
    done = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task.__str__()

    class Meta:
        verbose_name = _('Tarea de usuario')
        verbose_name_plural = _('Tareas de usuarios')


class Exercise(Model):
    name = models.CharField(_('name'), max_length=20)
    description = models.TextField(_('descripcion'), )
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Exercise')
        verbose_name_plural = _('Exercises')


class Attendance(Model):
    person_membership = models.ForeignKey(PersonMembership, null=True)
    exercises = models.ManyToManyField(Exercise)

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(User)

    class Meta:
        verbose_name = _('Attendance')
        verbose_name_plural = _('Attendances')
        permissions = (
            ("view_last_10_attendances", "Can view last 10 attendances per person"),
            ("add_exercise_to_attendance", "Can add exercise to attendance"),
        )

    def is_past_due(self):
        if date.today() > self.created_at.date():
            return True
        return False

    def __unicode__(self):
        return self.created_at


Person.get_active_membership_of_person = property(
    lambda s: PersonMembership.objects.filter(person=s, to__gt=timezone.now).first())

Person.last_attendance = property(
    lambda s: Attendance.objects.filter(person_membership__person=s).order_by('-created_at').first())

src/memberships/models.py
from django.db import models

# Create your models here.

src/memberships/forms.py
from django.utils.translation import ugettext as _
from django.forms import ModelForm

from main.functions import add_class, add_class_date_picker
from main.models import Membership
from store.models import Product


class MembershipForm(ModelForm):
    form_meta = {'title': _('Nueva Membresia'), }

    class Meta:
        model = Membership
        exclude = ("product",)

    def __init__(self, *args, **kwargs):
        super(MembershipForm, self).__init__(*args, **kwargs)
        add_class(self, ['duration_frequency', 'duration_type', 'limit_visits_per_day', 'is_active'])
        add_class_date_picker(self, ['date_end'])


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'price',)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        add_class(self, ['name', 'price'])

src/memberships/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from main.functions import generate_tasks_when

from main.models import Membership, DURATION_TYPES, ENTRIES_LIMIT_DAILY
from memberships.forms import MembershipForm, ProductForm
from memberships.functions import get_membership_or_404, get_category_membership, get_code_product_membership


@login_required
@permission_required('main.view_memberships', raise_exception=True)
def home(request):
    title = 'memberships'
    memberships = Membership.objects.all()
    return render(request, "memberships/home.html", locals())


@permission_required('main.add_membership')
@login_required
def new(request):
    title = _('new membership')
    if request.POST:
        form = MembershipForm(request.POST)
        form_product = ProductForm(request.POST)
        if form_product.is_valid() and form.is_valid():
            product = form_product.save(commit=False)
            product.category = get_category_membership()
            product.code = get_code_product_membership()
            product.save()

            member = form.save(commit=False)
            member.product = product
            member.save()
            generate_tasks_when(request, 'on_member_created', member)
            return redirect(reverse("memberships:home"))
    else:
        form = MembershipForm()
        form_product = ProductForm()
    form.DURATION_TYPES = DURATION_TYPES
    form.ENTRIES_LIMIT_DAILY = ENTRIES_LIMIT_DAILY
    return render(request, "memberships/form.html", locals())


@login_required
def edit(request, id):
    title = _('edit membership')
    membership = get_membership_or_404(id)
    if request.POST:
        form = MembershipForm(request.POST, request.FILES, instance=membership)
        form_product = ProductForm(request.POST, request.FILES, instance=membership.product)
        if form_product.is_valid() and form.is_valid():
            form_product.save()
            form.save()
            return redirect(reverse('memberships:home'))
    else:
        form = MembershipForm(instance=membership)
        form_product = ProductForm(instance=membership.product)
    form.DURATION_TYPES = DURATION_TYPES
    return render(request, 'memberships/form.html', locals())


@login_required
def delete(request, id):
    membership = get_membership_or_404(id)
    membership.delete()
    messages.add_message(request, messages.SUCCESS, _('<strong>Success!</strong>panel has been deleted.'))
    return redirect(reverse('memberships:home'))

src/memberships/templates/memberships/form.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% load static %}
{% block breadcrumb %}
    <li>
        <a href="{% url 'memberships:home' %}">{% trans 'memberships'|capfirst %}</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        <a>{% trans title|capfirst %}</a>
    </li>
{% endblock %}
{% block content %}
    <div class="portlet light">
        <h1 class="title">{% if not member %} {{ form.form_meta.title }}{% else %} Actualizando
            Membresia {% endif %}</h1>

        <form role="form" action="." method="post" class="horizontal">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {% include 'hock/form_horizontal_field.html' with field=form_product.name %}
                </div>

                <div class="col-md-6">
                    {% include 'hock/form_horizontal_field.html' with field=form_product.price %}
                </div>

                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            {% include 'hock/form_horizontal_field.html' with field=form.duration_frequency %}
                        </div>
                        <div class="col-md-6">
                            {% include 'hock/form_horizontal_field.html' with field=form.duration_type %}
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    {% include 'hock/form_horizontal_field.html' with field=form.limit_visits_per_day %}
                </div>

                <div class="col-md-6">
                    <div class="col-md-6">
                        {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_promo %}
                    </div>
                    <div class="col-md-6">
                        {% include 'hock/form_horizontal_field.html' with field=form.date_end %}
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group form-md-checkboxes">
                        <label>{% trans 'allowed days' %}</label>

                        <div class="md-checkbox-inline">
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_monday %}
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_tuesday %}
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_wednesday %}
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_thursday %}
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_friday %}
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_saturday %}
                            {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_on_sunday %}

                        </div>
                    </div>
                </div>
                <br>
                <br>
                <div class="col-md-6">
                    {% include 'hock/form_horizontal_field_checkbox.html' with field=form.is_active %}
                </div>
            </div>
            <br>
            <input type="submit" class="btn btn-lg blue" value="{% trans 'save' %}"/>
        </form>
    </div>
{% endblock %}
{% block javascripts_custom %}
    <script type="text/javascript"
            src="{% static 'main/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
{% endblock %}
{% block scripts %}

    $('.date-picker').datepicker({
    format: 'dd/mm/yyyy',
    autoclose: true
    }).on('hide', function(e){
    $(this).addClass('edited');
    });

    if (!$('#id_is_promo').is(':checked')){
    $('#id_date_end').parent().hide();
    }

    $('#id_is_promo').change(function(){
    if ($('#id_is_promo').is(':checked')){
    $('#id_date_end').parent().show();
    }else{
    $('#id_date_end').parent().hide();
    }
    })
{% endblock %}

src/memberships/templates/memberships/home.html
{% extends 'main/layout.html' %}

{% load i18n %}
{% load thumbnail %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'memberships:home' %}">{% trans title|capfirst %}</a>
    </li>
{% endblock %}

{% block page_toolbar %}
    {% if perms.main.add_membership %}
    <a href="{% url 'memberships:new' %}" class="btn btn-fit-height blue pull-right">
        <span class="fa fa-plus"></span>
        Crear Membresia
    </a>
    {% endif %}
{% endblock %}

{% block content %}
    {% if memberships %}
        <div class="row">
            {% for membership in memberships %}
                <div class="col-md-4">
                    <div class="portlet light">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-cogs font-green-sharp"></i>
                                <span class="caption-subject font-green-sharp bold uppercase">{{ membership.product.name }}</span>
                                <span class="caption-helper"></span>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="list-group">
                                <a class="list-group-item" href="javascript:;">
                                    {% trans 'duration' %}: {{ membership.duration_frequency }} {{ membership.get_duration_type_display }}
                                </a>
                                <a class="list-group-item" href="javascript:;">
                                    {% trans 'allowed days' %}: {{ membership.allowed_days }}
                                </a>
                                {% if membership.is_promo %}
                                <a class="list-group-item" href="javascript:;">
                                    {% trans 'promo available until' %}: {{ membership.date_end }}
                                </a>
                                {% endif %}
                                <a class="list-group-item" href="javascript:;">
                                    {% trans 'members' %}: {{ membership.get_count_members }}
                                </a>
                            </div>
                            <div class="btn-group btn-group-justified">
                                <a class="btn" href="{% url 'memberships:edit' membership.id %}">
                                    <span class="fa fa-edit"></span>
                                    Editar
                                </a>
                                <a class="btn delete_link" href="{% url 'memberships:delete' membership.id %}">
                                    <span class="fa fa-trash"></span>
                                    Eliminar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                {% endif %}
            {% endfor %}
            </div>

    {% else %}
        <p class="text-center">
            <em>No tienes membresias aún. <a href="{% url 'memberships:new' %}">Puedes crear un membresia aquí</a></em>
        </p>
    {% endif %}
{% endblock %}

{% block scripts %}
    $('.delete_link').click(function (e) {
    if (!confirm("Are you sure?")) {
    e.preventDefault();
    return false;
    }
    });
{% endblock %}